using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardInfoList : MonoBehaviour
{
    [SerializeField] List<cardInfo> AT_WX02_A_CardInfo_list = new List<cardInfo>();
    [SerializeField] List<cardInfo> DC_W01_T_CardInfo_list = new List<cardInfo>();
    [SerializeField] List<cardInfo> LB_W02_T_CardInfo_list = new List<cardInfo>();
    [SerializeField] List<cardInfo> P3_S01_T_CardInfo_list = new List<cardInfo>();

    public cardInfo Convert(string cardNo)
    {
        switch (cardNo)
        {
            case "AT_WX02_A01":
                return AT_WX02_A_CardInfo_list[0];
            case "AT_WX02_A02":
                return AT_WX02_A_CardInfo_list[1];
            case "AT_WX02_A03":
                return AT_WX02_A_CardInfo_list[2];
            case "AT_WX02_A04":
                return AT_WX02_A_CardInfo_list[3];
            case "AT_WX02_A05":
                return AT_WX02_A_CardInfo_list[4];
            case "AT_WX02_A06":
                return AT_WX02_A_CardInfo_list[5];
            case "AT_WX02_A07":
                return AT_WX02_A_CardInfo_list[6];
            case "AT_WX02_A08":
                return AT_WX02_A_CardInfo_list[7];
            case "AT_WX02_A09":
                return AT_WX02_A_CardInfo_list[8];
            case "AT_WX02_A10":
                return AT_WX02_A_CardInfo_list[9];
            case "AT_WX02_A11":
                return AT_WX02_A_CardInfo_list[10];
            case "AT_WX02_A12":
                return AT_WX02_A_CardInfo_list[11];
            case "AT_WX02_A13":
                return AT_WX02_A_CardInfo_list[12];
            case "DC_W01_01T":
                return DC_W01_T_CardInfo_list[0];
            case "DC_W01_02T":
                return DC_W01_T_CardInfo_list[1];
            case "DC_W01_03T":
                return DC_W01_T_CardInfo_list[2];
            case "DC_W01_04T":
                return DC_W01_T_CardInfo_list[3];
            case "DC_W01_05T":
                return DC_W01_T_CardInfo_list[4];
            case "DC_W01_06T":
                return DC_W01_T_CardInfo_list[5];
            case "DC_W01_07T":
                return DC_W01_T_CardInfo_list[6];
            case "DC_W01_08T":
                return DC_W01_T_CardInfo_list[7];
            case "DC_W01_09T":
                return DC_W01_T_CardInfo_list[8];
            case "DC_W01_10T":
                return DC_W01_T_CardInfo_list[9];
            case "DC_W01_11T":
                return DC_W01_T_CardInfo_list[10];
            case "DC_W01_12T":
                return DC_W01_T_CardInfo_list[11];
            case "DC_W01_13T":
                return DC_W01_T_CardInfo_list[12];
            case "DC_W01_14T":
                return DC_W01_T_CardInfo_list[13];
            case "DC_W01_15T":
                return DC_W01_T_CardInfo_list[14];
            case "DC_W01_16T":
                return DC_W01_T_CardInfo_list[15];
            case "DC_W01_17T":
                return DC_W01_T_CardInfo_list[16];
            case "DC_W01_18T":
                return DC_W01_T_CardInfo_list[17];
            case "DC_W01_19T":
                return DC_W01_T_CardInfo_list[18];
            case "DC_W01_20T":
                return DC_W01_T_CardInfo_list[19];
            case "LB_W02_01T":
                return LB_W02_T_CardInfo_list[0];
            case "LB_W02_02T":
                return LB_W02_T_CardInfo_list[1];
            case "LB_W02_03T":
                return LB_W02_T_CardInfo_list[2];
            case "LB_W02_04T":
                return LB_W02_T_CardInfo_list[3];
            case "LB_W02_05T":
                return LB_W02_T_CardInfo_list[4];
            case "LB_W02_06T":
                return LB_W02_T_CardInfo_list[5];
            case "LB_W02_07T":
                return LB_W02_T_CardInfo_list[6];
            case "LB_W02_08T":
                return LB_W02_T_CardInfo_list[7];
            case "LB_W02_09T":
                return LB_W02_T_CardInfo_list[8];
            case "LB_W02_10T":
                return LB_W02_T_CardInfo_list[9];
            case "LB_W02_11T":
                return LB_W02_T_CardInfo_list[10];
            case "LB_W02_12T":
                return LB_W02_T_CardInfo_list[11];
            case "LB_W02_13T":
                return LB_W02_T_CardInfo_list[12];
            case "LB_W02_14T":
                return LB_W02_T_CardInfo_list[13];
            case "LB_W02_15T":
                return LB_W02_T_CardInfo_list[14];
            case "LB_W02_16T":
                return LB_W02_T_CardInfo_list[15];
            case "LB_W02_17T":
                return LB_W02_T_CardInfo_list[16];
            case "LB_W02_18T":
                return LB_W02_T_CardInfo_list[17];
            case "LB_W02_19T":
                return LB_W02_T_CardInfo_list[18];
            case "LB_W02_20T":
                return LB_W02_T_CardInfo_list[19];
            case "P3_S01_01T":
                return P3_S01_T_CardInfo_list[0];
            case "P3_S01_02T":
                return P3_S01_T_CardInfo_list[1];
            case "P3_S01_03T":
                return P3_S01_T_CardInfo_list[2];
            case "P3_S01_04T":
                return P3_S01_T_CardInfo_list[3];
            case "P3_S01_05T":
                return P3_S01_T_CardInfo_list[4];
            case "P3_S01_06T":
                return P3_S01_T_CardInfo_list[5];
            case "P3_S01_07T":
                return P3_S01_T_CardInfo_list[6];
            case "P3_S01_08T":
                return P3_S01_T_CardInfo_list[7];
            case "P3_S01_09T":
                return P3_S01_T_CardInfo_list[8];
            case "P3_S01_10T":
                return P3_S01_T_CardInfo_list[9];
            case "P3_S01_11T":
                return P3_S01_T_CardInfo_list[10];
            case "P3_S01_12T":
                return P3_S01_T_CardInfo_list[11];
            case "P3_S01_13T":
                return P3_S01_T_CardInfo_list[12];
            case "P3_S01_14T":
                return P3_S01_T_CardInfo_list[13];
            case "P3_S01_15T":
                return P3_S01_T_CardInfo_list[14];
            case "P3_S01_16T":
                return P3_S01_T_CardInfo_list[15];
            case "P3_S01_17T":
                return P3_S01_T_CardInfo_list[16];
            case "P3_S01_18T":
                return P3_S01_T_CardInfo_list[17];
            case "P3_S01_19T":
                return P3_S01_T_CardInfo_list[18];
            case "P3_S01_20T":
                return P3_S01_T_CardInfo_list[19];
            default:
                return null;
        }
    }
}
