using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BattleModeCardList : MonoBehaviour
{
    public List<BattleModeCard> AdventureTimeList = new List<BattleModeCard>();
    public List<BattleModeCard> DC_2008TrialDeck = new List<BattleModeCard>();
    public List<BattleModeCard> LittleBusters_2008TrialDeck = new List<BattleModeCard>();
    public List<BattleModeCard> LittleBusters = new List<BattleModeCard>();
    public List<BattleModeCard> Persona3_2008TrialDeck = new List<BattleModeCard>();
    public List<BattleModeCard> Persona3 = new List<BattleModeCard>();

    public BattleModeCard ConvertCardNoToBattleModeCard(EnumController.CardNo num)
    {
        switch (num)
        {
            case EnumController.CardNo.AT_WX02_A01:
                return AdventureTimeList[0];
            case EnumController.CardNo.AT_WX02_A02:
                return AdventureTimeList[1];
            case EnumController.CardNo.AT_WX02_A03:
                return AdventureTimeList[2];
            case EnumController.CardNo.AT_WX02_A04:
                return AdventureTimeList[3];
            case EnumController.CardNo.AT_WX02_A05:
                return AdventureTimeList[4];
            case EnumController.CardNo.AT_WX02_A06:
                return AdventureTimeList[5];
            case EnumController.CardNo.AT_WX02_A07:
                return AdventureTimeList[6];
            case EnumController.CardNo.AT_WX02_A08:
                return AdventureTimeList[7];
            case EnumController.CardNo.AT_WX02_A09:
                return AdventureTimeList[8];
            case EnumController.CardNo.AT_WX02_A10:
                return AdventureTimeList[9];
            case EnumController.CardNo.AT_WX02_A11:
                return AdventureTimeList[10];
            case EnumController.CardNo.AT_WX02_A12:
                return AdventureTimeList[11];
            case EnumController.CardNo.AT_WX02_A13:
                return AdventureTimeList[12];
            case EnumController.CardNo.DC_W01_01T:
                return DC_2008TrialDeck[0];
            case EnumController.CardNo.DC_W01_02T:
                return DC_2008TrialDeck[1];
            case EnumController.CardNo.DC_W01_03T:
                return DC_2008TrialDeck[2];
            case EnumController.CardNo.DC_W01_04T:
                return DC_2008TrialDeck[3];
            case EnumController.CardNo.DC_W01_05T:
                return DC_2008TrialDeck[4];
            case EnumController.CardNo.DC_W01_06T:
                return DC_2008TrialDeck[5];
            case EnumController.CardNo.DC_W01_07T:
                return DC_2008TrialDeck[6];
            case EnumController.CardNo.DC_W01_08T:
                return DC_2008TrialDeck[7];
            case EnumController.CardNo.DC_W01_09T:
                return DC_2008TrialDeck[8];
            case EnumController.CardNo.DC_W01_10T:
                return DC_2008TrialDeck[9];
            case EnumController.CardNo.DC_W01_11T:
                return DC_2008TrialDeck[10];
            case EnumController.CardNo.DC_W01_12T:
                return DC_2008TrialDeck[11];
            case EnumController.CardNo.DC_W01_13T:
                return DC_2008TrialDeck[12];
            case EnumController.CardNo.DC_W01_14T:
                return DC_2008TrialDeck[13];
            case EnumController.CardNo.DC_W01_15T:
                return DC_2008TrialDeck[14];
            case EnumController.CardNo.DC_W01_16T:
                return DC_2008TrialDeck[15];
            case EnumController.CardNo.DC_W01_17T:
                return DC_2008TrialDeck[16];
            case EnumController.CardNo.DC_W01_18T:
                return DC_2008TrialDeck[17];
            case EnumController.CardNo.DC_W01_19T:
                return DC_2008TrialDeck[18];
            case EnumController.CardNo.DC_W01_20T:
                return DC_2008TrialDeck[19];
            case EnumController.CardNo.LB_W02_01T:
                return LittleBusters_2008TrialDeck[0];
            case EnumController.CardNo.LB_W02_02T:
                return LittleBusters_2008TrialDeck[1];
            case EnumController.CardNo.LB_W02_03T:
                return LittleBusters_2008TrialDeck[2];
            case EnumController.CardNo.LB_W02_04T:
                return LittleBusters_2008TrialDeck[3];
            case EnumController.CardNo.LB_W02_05T:
                return LittleBusters_2008TrialDeck[4];
            case EnumController.CardNo.LB_W02_06T:
                return LittleBusters_2008TrialDeck[5];
            case EnumController.CardNo.LB_W02_07T:
                return LittleBusters_2008TrialDeck[6];
            case EnumController.CardNo.LB_W02_08T:
                return LittleBusters_2008TrialDeck[7];
            case EnumController.CardNo.LB_W02_09T:
                return LittleBusters_2008TrialDeck[8];
            case EnumController.CardNo.LB_W02_10T:
                return LittleBusters_2008TrialDeck[9];
            case EnumController.CardNo.LB_W02_11T:
                return LittleBusters_2008TrialDeck[10];
            case EnumController.CardNo.LB_W02_12T:
                return LittleBusters_2008TrialDeck[11];
            case EnumController.CardNo.LB_W02_13T:
                return LittleBusters_2008TrialDeck[12];
            case EnumController.CardNo.LB_W02_14T:
                return LittleBusters_2008TrialDeck[13];
            case EnumController.CardNo.LB_W02_15T:
                return LittleBusters_2008TrialDeck[14];
            case EnumController.CardNo.LB_W02_16T:
                return LittleBusters_2008TrialDeck[15];
            case EnumController.CardNo.LB_W02_17T:
                return LittleBusters_2008TrialDeck[16];
            case EnumController.CardNo.LB_W02_18T:
                return LittleBusters_2008TrialDeck[17];
            case EnumController.CardNo.LB_W02_19T:
                return LittleBusters_2008TrialDeck[18];
            case EnumController.CardNo.LB_W02_20T:
                return LittleBusters_2008TrialDeck[19];
            case EnumController.CardNo.P3_S01_01T:
                return Persona3_2008TrialDeck[0];
            case EnumController.CardNo.P3_S01_02T:
                return Persona3_2008TrialDeck[1];
            case EnumController.CardNo.P3_S01_03T:
                return Persona3_2008TrialDeck[2];
            case EnumController.CardNo.P3_S01_04T:
                return Persona3_2008TrialDeck[3];
            case EnumController.CardNo.P3_S01_05T:
                return Persona3_2008TrialDeck[4];
            case EnumController.CardNo.P3_S01_06T:
                return Persona3_2008TrialDeck[5];
            case EnumController.CardNo.P3_S01_07T:
                return Persona3_2008TrialDeck[6];
            case EnumController.CardNo.P3_S01_08T:
                return Persona3_2008TrialDeck[7];
            case EnumController.CardNo.P3_S01_09T:
                return Persona3_2008TrialDeck[8];
            case EnumController.CardNo.P3_S01_10T:
                return Persona3_2008TrialDeck[9];
            case EnumController.CardNo.P3_S01_11T:
                return Persona3_2008TrialDeck[10];
            case EnumController.CardNo.P3_S01_12T:
                return Persona3_2008TrialDeck[11];
            case EnumController.CardNo.P3_S01_13T:
                return Persona3_2008TrialDeck[12];
            case EnumController.CardNo.P3_S01_14T:
                return Persona3_2008TrialDeck[13];
            case EnumController.CardNo.P3_S01_15T:
                return Persona3_2008TrialDeck[14];
            case EnumController.CardNo.P3_S01_16T:
                return Persona3_2008TrialDeck[15];
            case EnumController.CardNo.P3_S01_17T:
                return Persona3_2008TrialDeck[16];
            case EnumController.CardNo.P3_S01_18T:
                return Persona3_2008TrialDeck[17];
            case EnumController.CardNo.P3_S01_19T:
                return Persona3_2008TrialDeck[18];
            case EnumController.CardNo.P3_S01_20T:
                return Persona3_2008TrialDeck[19];
            default:
                break;
        }
        switch (num)
        {
            case EnumController.CardNo.P3_S01_001:
                return Persona3[0];
            case EnumController.CardNo.P3_S01_002:
                return Persona3[1];
            case EnumController.CardNo.P3_S01_003:
                return Persona3[2];
            case EnumController.CardNo.P3_S01_004:
                return Persona3[3];
            case EnumController.CardNo.P3_S01_005:
                return Persona3[4];
            case EnumController.CardNo.P3_S01_006:
                return Persona3[5];
            case EnumController.CardNo.P3_S01_007:
                return Persona3[6];
            case EnumController.CardNo.P3_S01_008:
                return Persona3[7];
            case EnumController.CardNo.P3_S01_009:
                return Persona3[8];
            case EnumController.CardNo.P3_S01_010:
                return Persona3[9];
            case EnumController.CardNo.P3_S01_011:
                return Persona3[10];
            case EnumController.CardNo.P3_S01_012:
                return Persona3[11];
            case EnumController.CardNo.P3_S01_013:
                return Persona3[12];
            case EnumController.CardNo.P3_S01_014:
                return Persona3[13];
            case EnumController.CardNo.P3_S01_015:
                return Persona3[14];
            case EnumController.CardNo.P3_S01_016:
                return Persona3[15];
            case EnumController.CardNo.P3_S01_017:
                return Persona3[16];
            case EnumController.CardNo.P3_S01_018:
                return Persona3[17];
            case EnumController.CardNo.P3_S01_019:
                return Persona3[18];
            case EnumController.CardNo.P3_S01_020:
                return Persona3[19];
            case EnumController.CardNo.P3_S01_021:
                return Persona3[20];
            case EnumController.CardNo.P3_S01_022:
                return Persona3[21];
            case EnumController.CardNo.P3_S01_023:
                return Persona3[22];
            case EnumController.CardNo.P3_S01_024:
                return Persona3[23];
            case EnumController.CardNo.P3_S01_025:
                return Persona3[24];
            case EnumController.CardNo.P3_S01_026:
                return Persona3[25];
            case EnumController.CardNo.P3_S01_027:
                return Persona3[26];
            case EnumController.CardNo.P3_S01_028:
                return Persona3[27];
            case EnumController.CardNo.P3_S01_029:
                return Persona3[28];
            case EnumController.CardNo.P3_S01_030:
                return Persona3[29];
            case EnumController.CardNo.P3_S01_031:
                return Persona3[30];
            case EnumController.CardNo.P3_S01_032:
                return Persona3[31];
            case EnumController.CardNo.P3_S01_033:
                return Persona3[32];
            case EnumController.CardNo.P3_S01_034:
                return Persona3[33];
            case EnumController.CardNo.P3_S01_035:
                return Persona3[34];
            case EnumController.CardNo.P3_S01_036:
                return Persona3[35];
            case EnumController.CardNo.P3_S01_037:
                return Persona3[36];
            case EnumController.CardNo.P3_S01_038:
                return Persona3[37];
            case EnumController.CardNo.P3_S01_039:
                return Persona3[38];
            case EnumController.CardNo.P3_S01_040:
                return Persona3[39];
            case EnumController.CardNo.P3_S01_041:
                return Persona3[40];
            case EnumController.CardNo.P3_S01_042:
                return Persona3[41];
            case EnumController.CardNo.P3_S01_043:
                return Persona3[42];
            case EnumController.CardNo.P3_S01_044:
                return Persona3[43];
            case EnumController.CardNo.P3_S01_045:
                return Persona3[44];
            case EnumController.CardNo.P3_S01_046:
                return Persona3[45];
            case EnumController.CardNo.P3_S01_047:
                return Persona3[46];
            case EnumController.CardNo.P3_S01_048:
                return Persona3[47];
            case EnumController.CardNo.P3_S01_049:
                return Persona3[48];
            case EnumController.CardNo.P3_S01_050:
                return Persona3[49];
            case EnumController.CardNo.P3_S01_051:
                return Persona3[50];
            case EnumController.CardNo.P3_S01_052:
                return Persona3[51];
            case EnumController.CardNo.P3_S01_053:
                return Persona3[52];
            case EnumController.CardNo.P3_S01_054:
                return Persona3[53];
            case EnumController.CardNo.P3_S01_055:
                return Persona3[54];
            case EnumController.CardNo.P3_S01_056:
                return Persona3[55];
            case EnumController.CardNo.P3_S01_057:
                return Persona3[56];
            case EnumController.CardNo.P3_S01_058:
                return Persona3[57];
            case EnumController.CardNo.P3_S01_059:
                return Persona3[58];
            case EnumController.CardNo.P3_S01_060:
                return Persona3[59];
            case EnumController.CardNo.P3_S01_061:
                return Persona3[60];
            case EnumController.CardNo.P3_S01_062:
                return Persona3[61];
            case EnumController.CardNo.P3_S01_063:
                return Persona3[62];
            case EnumController.CardNo.P3_S01_064:
                return Persona3[63];
            case EnumController.CardNo.P3_S01_065:
                return Persona3[64];
            case EnumController.CardNo.P3_S01_066:
                return Persona3[65];
            case EnumController.CardNo.P3_S01_067:
                return Persona3[66];
            case EnumController.CardNo.P3_S01_068:
                return Persona3[67];
            case EnumController.CardNo.P3_S01_069:
                return Persona3[68];
            case EnumController.CardNo.P3_S01_070:
                return Persona3[69];
            default: 
                break;
        }
        switch (num)
        {
            case EnumController.CardNo.P3_S01_071:
                return Persona3[70];
            case EnumController.CardNo.P3_S01_072:
                return Persona3[71];
            case EnumController.CardNo.P3_S01_073:
                return Persona3[72];
            case EnumController.CardNo.P3_S01_074:
                return Persona3[73];
            case EnumController.CardNo.P3_S01_075:
                return Persona3[74];
            case EnumController.CardNo.P3_S01_076:
                return Persona3[75];
            case EnumController.CardNo.P3_S01_077:
                return Persona3[76];
            case EnumController.CardNo.P3_S01_078:
                return Persona3[77];
            case EnumController.CardNo.P3_S01_079:
                return Persona3[78];
            case EnumController.CardNo.P3_S01_080:
                return Persona3[79];
            case EnumController.CardNo.P3_S01_081:
                return Persona3[80];
            case EnumController.CardNo.P3_S01_082:
                return Persona3[81];
            case EnumController.CardNo.P3_S01_083:
                return Persona3[82];
            case EnumController.CardNo.P3_S01_084:
                return Persona3[83];
            case EnumController.CardNo.P3_S01_085:
                return Persona3[84];
            case EnumController.CardNo.P3_S01_086:
                return Persona3[85];
            case EnumController.CardNo.P3_S01_087:
                return Persona3[86];
            case EnumController.CardNo.P3_S01_088:
                return Persona3[87];
            case EnumController.CardNo.P3_S01_089:
                return Persona3[88];
            case EnumController.CardNo.P3_S01_090:
                return Persona3[89];
            case EnumController.CardNo.P3_S01_091:
                return Persona3[90];
            case EnumController.CardNo.P3_S01_092:
                return Persona3[91];
            case EnumController.CardNo.P3_S01_093:
                return Persona3[92];
            case EnumController.CardNo.P3_S01_094:
                return Persona3[93];
            case EnumController.CardNo.P3_S01_095:
                return Persona3[94];
            case EnumController.CardNo.P3_S01_096:
                return Persona3[95];
            case EnumController.CardNo.P3_S01_097:
                return Persona3[96];
            case EnumController.CardNo.P3_S01_098:
                return Persona3[97];
            case EnumController.CardNo.P3_S01_099:
                return Persona3[98];
            case EnumController.CardNo.P3_S01_100:
                return Persona3[99];
            default:
                break;
        }
        switch (num)
        {
            case EnumController.CardNo.LB_W02_001:
                return LittleBusters[0];
            case EnumController.CardNo.LB_W02_002:
                return LittleBusters[1];
            case EnumController.CardNo.LB_W02_003:
                return LittleBusters[2];
            case EnumController.CardNo.LB_W02_004:
                return LittleBusters[3];
            case EnumController.CardNo.LB_W02_005:
                return LittleBusters[4];
            case EnumController.CardNo.LB_W02_006:
                return LittleBusters[5];
            case EnumController.CardNo.LB_W02_007:
                return LittleBusters[6];
            case EnumController.CardNo.LB_W02_008:
                return LittleBusters[7];
            case EnumController.CardNo.LB_W02_009:
                return LittleBusters[8];
            case EnumController.CardNo.LB_W02_010:
                return LittleBusters[9];
            case EnumController.CardNo.LB_W02_011:
                return LittleBusters[10];
            case EnumController.CardNo.LB_W02_012:
                return LittleBusters[11];
            case EnumController.CardNo.LB_W02_013:
                return LittleBusters[12];
            case EnumController.CardNo.LB_W02_014:
                return LittleBusters[13];
            case EnumController.CardNo.LB_W02_015:
                return LittleBusters[14];
            case EnumController.CardNo.LB_W02_016:
                return LittleBusters[15];
            case EnumController.CardNo.LB_W02_017:
                return LittleBusters[16];
            case EnumController.CardNo.LB_W02_018:
                return LittleBusters[17];
            case EnumController.CardNo.LB_W02_019:
                return LittleBusters[18];
            case EnumController.CardNo.LB_W02_020:
                return LittleBusters[19];
            case EnumController.CardNo.LB_W02_021:
                return LittleBusters[20];
            case EnumController.CardNo.LB_W02_022:
                return LittleBusters[21];
            case EnumController.CardNo.LB_W02_023:
                return LittleBusters[22];
            case EnumController.CardNo.LB_W02_024:
                return LittleBusters[23];
            case EnumController.CardNo.LB_W02_025:
                return LittleBusters[24];
            case EnumController.CardNo.LB_W02_026:
                return LittleBusters[25];
            case EnumController.CardNo.LB_W02_027:
                return LittleBusters[26];
            case EnumController.CardNo.LB_W02_028:
                return LittleBusters[27];
            case EnumController.CardNo.LB_W02_029:
                return LittleBusters[28];
            case EnumController.CardNo.LB_W02_030:
                return LittleBusters[29];
            case EnumController.CardNo.LB_W02_031:
                return LittleBusters[30];
            case EnumController.CardNo.LB_W02_032:
                return LittleBusters[31];
            case EnumController.CardNo.LB_W02_033:
                return LittleBusters[32];
            case EnumController.CardNo.LB_W02_034:
                return LittleBusters[33];
            case EnumController.CardNo.LB_W02_035:
                return LittleBusters[34];
            case EnumController.CardNo.LB_W02_036:
                return LittleBusters[35];
            case EnumController.CardNo.LB_W02_037:
                return LittleBusters[36];
            case EnumController.CardNo.LB_W02_038:
                return LittleBusters[37];
            case EnumController.CardNo.LB_W02_039:
                return LittleBusters[38];
            case EnumController.CardNo.LB_W02_040:
                return LittleBusters[39];
            case EnumController.CardNo.LB_W02_041:
                return LittleBusters[40];
            case EnumController.CardNo.LB_W02_042:
                return LittleBusters[41];
            case EnumController.CardNo.LB_W02_043:
                return LittleBusters[42];
            case EnumController.CardNo.LB_W02_044:
                return LittleBusters[43];
            case EnumController.CardNo.LB_W02_045:
                return LittleBusters[44];
            case EnumController.CardNo.LB_W02_046:
                return LittleBusters[45];
            case EnumController.CardNo.LB_W02_047:
                return LittleBusters[46];
            case EnumController.CardNo.LB_W02_048:
                return LittleBusters[47];
            case EnumController.CardNo.LB_W02_049:
                return LittleBusters[48];
            case EnumController.CardNo.LB_W02_050:
                return LittleBusters[49];
            case EnumController.CardNo.LB_W02_051:
                return LittleBusters[50];
            case EnumController.CardNo.LB_W02_052:
                return LittleBusters[51];
            case EnumController.CardNo.LB_W02_053:
                return LittleBusters[52];
            case EnumController.CardNo.LB_W02_054:
                return LittleBusters[53];
            case EnumController.CardNo.LB_W02_055:
                return LittleBusters[54];
            case EnumController.CardNo.LB_W02_056:
                return LittleBusters[55];
            case EnumController.CardNo.LB_W02_057:
                return LittleBusters[56];
            case EnumController.CardNo.LB_W02_058:
                return LittleBusters[57];
            case EnumController.CardNo.LB_W02_059:
                return LittleBusters[58];
            case EnumController.CardNo.LB_W02_060:
                return LittleBusters[59];
            case EnumController.CardNo.LB_W02_061:
                return LittleBusters[60];
            case EnumController.CardNo.LB_W02_062:
                return LittleBusters[61];
            case EnumController.CardNo.LB_W02_063:
                return LittleBusters[62];
            case EnumController.CardNo.LB_W02_064:
                return LittleBusters[63];
            case EnumController.CardNo.LB_W02_065:
                return LittleBusters[64];
            case EnumController.CardNo.LB_W02_066:
                return LittleBusters[65];
            case EnumController.CardNo.LB_W02_067:
                return LittleBusters[66];
            case EnumController.CardNo.LB_W02_068:
                return LittleBusters[67];
            case EnumController.CardNo.LB_W02_069:
                return LittleBusters[68];
            case EnumController.CardNo.LB_W02_070:
                return LittleBusters[69];
            case EnumController.CardNo.LB_W02_071:
                return LittleBusters[70];
            case EnumController.CardNo.LB_W02_072:
                return LittleBusters[71];
            case EnumController.CardNo.LB_W02_073:
                return LittleBusters[72];
            case EnumController.CardNo.LB_W02_074:
                return LittleBusters[73];
            case EnumController.CardNo.LB_W02_075:
                return LittleBusters[74];
            case EnumController.CardNo.LB_W02_076:
                return LittleBusters[75];
            case EnumController.CardNo.LB_W02_077:
                return LittleBusters[76];
            case EnumController.CardNo.LB_W02_078:
                return LittleBusters[77];
            case EnumController.CardNo.LB_W02_079:
                return LittleBusters[78];
            case EnumController.CardNo.LB_W02_080:
                return LittleBusters[79];
            case EnumController.CardNo.LB_W02_081:
                return LittleBusters[80];
            case EnumController.CardNo.LB_W02_082:
                return LittleBusters[81];
            case EnumController.CardNo.LB_W02_083:
                return LittleBusters[82];
            case EnumController.CardNo.LB_W02_084:
                return LittleBusters[83];
            case EnumController.CardNo.LB_W02_085:
                return LittleBusters[84];
            case EnumController.CardNo.LB_W02_086:
                return LittleBusters[85];
            case EnumController.CardNo.LB_W02_087:
                return LittleBusters[86];
            case EnumController.CardNo.LB_W02_088:
                return LittleBusters[87];
            case EnumController.CardNo.LB_W02_089:
                return LittleBusters[88];
            case EnumController.CardNo.LB_W02_090:
                return LittleBusters[89];
            case EnumController.CardNo.LB_W02_091:
                return LittleBusters[90];
            case EnumController.CardNo.LB_W02_092:
                return LittleBusters[91];
            case EnumController.CardNo.LB_W02_093:
                return LittleBusters[92];
            case EnumController.CardNo.LB_W02_094:
                return LittleBusters[93];
            case EnumController.CardNo.LB_W02_095:
                return LittleBusters[94];
            case EnumController.CardNo.LB_W02_096:
                return LittleBusters[95];
            case EnumController.CardNo.LB_W02_097:
                return LittleBusters[96];
            case EnumController.CardNo.LB_W02_098:
                return LittleBusters[97];
            case EnumController.CardNo.LB_W02_099:
                return LittleBusters[98];
            case EnumController.CardNo.LB_W02_100:
                return LittleBusters[99];
            default:
                return null;
        }
    }

    public BattleModeCard ConvertStringToCardNo(string cardNo)
    {
        switch (cardNo)
        {
            case "AT_WX02_A01":
                return AdventureTimeList[0];
            case "AT_WX02_A02":
                return AdventureTimeList[1];
            case "AT_WX02_A03":
                return AdventureTimeList[2];
            case "AT_WX02_A04":
                return AdventureTimeList[3];
            case "AT_WX02_A05":
                return AdventureTimeList[4];
            case "AT_WX02_A06":
                return AdventureTimeList[5];
            case "AT_WX02_A07":
                return AdventureTimeList[6];
            case "AT_WX02_A08":
                return AdventureTimeList[7];
            case "AT_WX02_A09":
                return AdventureTimeList[8];
            case "AT_WX02_A10":
                return AdventureTimeList[9];
            case "AT_WX02_A11":
                return AdventureTimeList[10];
            case "AT_WX02_A12":
                return AdventureTimeList[11];
            case "AT_WX02_A13":
                return AdventureTimeList[12];
            case "DC_W01_01T":
                return DC_2008TrialDeck[0];
            case "DC_W01_02T":
                return DC_2008TrialDeck[1];
            case "DC_W01_03T":
                return DC_2008TrialDeck[2];
            case "DC_W01_04T":
                return DC_2008TrialDeck[3];
            case "DC_W01_05T":
                return DC_2008TrialDeck[4];
            case "DC_W01_06T":
                return DC_2008TrialDeck[5];
            case "DC_W01_07T":
                return DC_2008TrialDeck[6];
            case "DC_W01_08T":
                return DC_2008TrialDeck[7];
            case "DC_W01_09T":
                return DC_2008TrialDeck[8];
            case "DC_W01_10T":
                return DC_2008TrialDeck[9];
            case "DC_W01_11T":
                return DC_2008TrialDeck[10];
            case "DC_W01_12T":
                return DC_2008TrialDeck[11];
            case "DC_W01_13T":
                return DC_2008TrialDeck[12];
            case "DC_W01_14T":
                return DC_2008TrialDeck[13];
            case "DC_W01_15T":
                return DC_2008TrialDeck[14];
            case "DC_W01_16T":
                return DC_2008TrialDeck[15];
            case "DC_W01_17T":
                return DC_2008TrialDeck[16];
            case "DC_W01_18T":
                return DC_2008TrialDeck[17];
            case "DC_W01_19T":
                return DC_2008TrialDeck[18];
            case "DC_W01_20T":
                return DC_2008TrialDeck[19];
            case "LB_W02_01T":
                return LittleBusters_2008TrialDeck[0];
            case "LB_W02_02T":
                return LittleBusters_2008TrialDeck[1];
            case "LB_W02_03T":
                return LittleBusters_2008TrialDeck[2];
            case "LB_W02_04T":
                return LittleBusters_2008TrialDeck[3];
            case "LB_W02_05T":
                return LittleBusters_2008TrialDeck[4];
            case "LB_W02_06T":
                return LittleBusters_2008TrialDeck[5];
            case "LB_W02_07T":
                return LittleBusters_2008TrialDeck[6];
            case "LB_W02_08T":
                return LittleBusters_2008TrialDeck[7];
            case "LB_W02_09T":
                return LittleBusters_2008TrialDeck[8];
            case "LB_W02_10T":
                return LittleBusters_2008TrialDeck[9];
            case "LB_W02_11T":
                return LittleBusters_2008TrialDeck[10];
            case "LB_W02_12T":
                return LittleBusters_2008TrialDeck[11];
            case "LB_W02_13T":
                return LittleBusters_2008TrialDeck[12];
            case "LB_W02_14T":
                return LittleBusters_2008TrialDeck[13];
            case "LB_W02_15T":
                return LittleBusters_2008TrialDeck[14];
            case "LB_W02_16T":
                return LittleBusters_2008TrialDeck[15];
            case "LB_W02_17T":
                return LittleBusters_2008TrialDeck[16];
            case "LB_W02_18T":
                return LittleBusters_2008TrialDeck[17];
            case "LB_W02_19T":
                return LittleBusters_2008TrialDeck[18];
            case "LB_W02_20T":
                return LittleBusters_2008TrialDeck[19];
            case "P3_S01_01T":
                return Persona3_2008TrialDeck[0];
            case "P3_S01_02T":
                return Persona3_2008TrialDeck[1];
            case "P3_S01_03T":
                return Persona3_2008TrialDeck[2];
            case "P3_S01_04T":
                return Persona3_2008TrialDeck[3];
            case "P3_S01_05T":
                return Persona3_2008TrialDeck[4];
            case "P3_S01_06T":
                return Persona3_2008TrialDeck[5];
            case "P3_S01_07T":
                return Persona3_2008TrialDeck[6];
            case "P3_S01_08T":
                return Persona3_2008TrialDeck[7];
            case "P3_S01_09T":
                return Persona3_2008TrialDeck[8];
            case "P3_S01_10T":
                return Persona3_2008TrialDeck[9];
            case "P3_S01_11T":
                return Persona3_2008TrialDeck[10];
            case "P3_S01_12T":
                return Persona3_2008TrialDeck[11];
            case "P3_S01_13T":
                return Persona3_2008TrialDeck[12];
            case "P3_S01_14T":
                return Persona3_2008TrialDeck[13];
            case "P3_S01_15T":
                return Persona3_2008TrialDeck[14];
            case "P3_S01_16T":
                return Persona3_2008TrialDeck[15];
            case "P3_S01_17T":
                return Persona3_2008TrialDeck[16];
            case "P3_S01_18T":
                return Persona3_2008TrialDeck[17];
            case "P3_S01_19T":
                return Persona3_2008TrialDeck[18];
            case "P3_S01_20T":
                return Persona3_2008TrialDeck[19];
            case "P3_S01_001":
                return Persona3[0];
            case "P3_S01_002":
                return Persona3[1];
            case "P3_S01_003":
                return Persona3[2];
            case "P3_S01_004":
                return Persona3[3];
            case "P3_S01_005":
                return Persona3[4];
            case "P3_S01_006":
                return Persona3[5];
            case "P3_S01_007":
                return Persona3[6];
            case "P3_S01_008":
                return Persona3[7];
            case "P3_S01_009":
                return Persona3[8];
            case "P3_S01_010":
                return Persona3[9];
            case "P3_S01_011":
                return Persona3[10];
            case "P3_S01_012":
                return Persona3[11];
            case "P3_S01_013":
                return Persona3[12];
            case "P3_S01_014":
                return Persona3[13];
            case "P3_S01_015":
                return Persona3[14];
            case "P3_S01_016":
                return Persona3[15];
            case "P3_S01_017":
                return Persona3[16];
            case "P3_S01_018":
                return Persona3[17];
            case "P3_S01_019":
                return Persona3[18];
            case "P3_S01_020":
                return Persona3[19];
            case "P3_S01_021":
                return Persona3[20];
            case "P3_S01_022":
                return Persona3[21];
            case "P3_S01_023":
                return Persona3[22];
            case "P3_S01_024":
                return Persona3[23];
            case "P3_S01_025":
                return Persona3[24];
            case "P3_S01_026":
                return Persona3[25];
            case "P3_S01_027":
                return Persona3[26];
            case "P3_S01_028":
                return Persona3[27];
            case "P3_S01_029":
                return Persona3[28];
            case "P3_S01_030":
                return Persona3[29];
            default:
                break;
        }
        switch (cardNo)
        {
            case "P3_S01_031":
                return Persona3[30];
            case "P3_S01_032":
                return Persona3[31];
            case "P3_S01_033":
                return Persona3[32];
            case "P3_S01_034":
                return Persona3[33];
            case "P3_S01_035":
                return Persona3[34];
            case "P3_S01_036":
                return Persona3[35];
            case "P3_S01_037":
                return Persona3[36];
            case "P3_S01_038":
                return Persona3[37];
            case "P3_S01_039":
                return Persona3[38];
            case "P3_S01_040":
                return Persona3[39];
            case "P3_S01_041":
                return Persona3[40];
            case "P3_S01_042":
                return Persona3[41];
            case "P3_S01_043":
                return Persona3[42];
            case "P3_S01_044":
                return Persona3[43];
            case "P3_S01_045":
                return Persona3[44];
            case "P3_S01_046":
                return Persona3[45];
            case "P3_S01_047":
                return Persona3[46];
            case "P3_S01_048":
                return Persona3[47];
            case "P3_S01_049":
                return Persona3[48];
            case "P3_S01_050":
                return Persona3[49];
            case "P3_S01_051":
                return Persona3[50];
            case "P3_S01_052":
                return Persona3[51];
            case "P3_S01_053":
                return Persona3[52];
            case "P3_S01_054":
                return Persona3[53];
            case "P3_S01_055":
                return Persona3[54];
            case "P3_S01_056":
                return Persona3[55];
            case "P3_S01_057":
                return Persona3[56];
            case "P3_S01_058":
                return Persona3[57];
            case "P3_S01_059":
                return Persona3[58];
            case "P3_S01_060":
                return Persona3[59];
            case "P3_S01_061":
                return Persona3[60];
            case "P3_S01_062":
                return Persona3[61];
            case "P3_S01_063":
                return Persona3[62];
            case "P3_S01_064":
                return Persona3[63];
            case "P3_S01_065":
                return Persona3[64];
            case "P3_S01_066":
                return Persona3[65];
            case "P3_S01_067":
                return Persona3[66];
            case "P3_S01_068":
                return Persona3[67];
            case "P3_S01_069":
                return Persona3[68];
            case "P3_S01_070":
                return Persona3[69];
            case "P3_S01_071":
                return Persona3[70];
            case "P3_S01_072":
                return Persona3[71];
            case "P3_S01_073":
                return Persona3[72];
            case "P3_S01_074":
                return Persona3[73];
            case "P3_S01_075":
                return Persona3[74];
            case "P3_S01_076":
                return Persona3[75];
            case "P3_S01_077":
                return Persona3[76];
            case "P3_S01_078":
                return Persona3[77];
            case "P3_S01_079":
                return Persona3[78];
            case "P3_S01_080":
                return Persona3[79];
            case "P3_S01_081":
                return Persona3[80];
            case "P3_S01_082":
                return Persona3[81];
            case "P3_S01_083":
                return Persona3[82];
            case "P3_S01_084":
                return Persona3[83];
            case "P3_S01_085":
                return Persona3[84];
            case "P3_S01_086":
                return Persona3[85];
            case "P3_S01_087":
                return Persona3[86];
            case "P3_S01_088":
                return Persona3[87];
            case "P3_S01_089":
                return Persona3[88];
            case "P3_S01_090":
                return Persona3[89];
            case "P3_S01_091":
                return Persona3[90];
            case "P3_S01_092":
                return Persona3[91];
            case "P3_S01_093":
                return Persona3[92];
            case "P3_S01_094":
                return Persona3[93];
            case "P3_S01_095":
                return Persona3[94];
            case "P3_S01_096":
                return Persona3[95];
            case "P3_S01_097":
                return Persona3[96];
            case "P3_S01_098":
                return Persona3[97];
            case "P3_S01_099":
                return Persona3[98];
            case "P3_S01_100":
                return Persona3[99];
            default:
                break;
        }
        switch (cardNo)
        {
            case "LB_W02_001":
                return LittleBusters[0];
            case "LB_W02_002":
                return LittleBusters[1];
            case "LB_W02_003":
                return LittleBusters[2];
            case "LB_W02_004":
                return LittleBusters[3];
            case "LB_W02_005":
                return LittleBusters[4];
            case "LB_W02_006":
                return LittleBusters[5];
            case "LB_W02_007":
                return LittleBusters[6];
            case "LB_W02_008":
                return LittleBusters[7];
            case "LB_W02_009":
                return LittleBusters[8];
            case "LB_W02_010":
                return LittleBusters[9];
            case "LB_W02_011":
                return LittleBusters[10];
            case "LB_W02_012":
                return LittleBusters[11];
            case "LB_W02_013":
                return LittleBusters[12];
            case "LB_W02_014":
                return LittleBusters[13];
            case "LB_W02_015":
                return LittleBusters[14];
            case "LB_W02_016":
                return LittleBusters[15];
            case "LB_W02_017":
                return LittleBusters[16];
            case "LB_W02_018":
                return LittleBusters[17];
            case "LB_W02_019":
                return LittleBusters[18];
            case "LB_W02_020":
                return LittleBusters[19];
            case "LB_W02_021":
                return LittleBusters[20];
            case "LB_W02_022":
                return LittleBusters[21];
            case "LB_W02_023":
                return LittleBusters[22];
            case "LB_W02_024":
                return LittleBusters[23];
            case "LB_W02_025":
                return LittleBusters[24];
            case "LB_W02_026":
                return LittleBusters[25];
            case "LB_W02_027":
                return LittleBusters[26];
            case "LB_W02_028":
                return LittleBusters[27];
            case "LB_W02_029":
                return LittleBusters[28];
            case "LB_W02_030":
                return LittleBusters[29];
            case "LB_W02_031":
                return LittleBusters[30];
            case "LB_W02_032":
                return LittleBusters[31];
            case "LB_W02_033":
                return LittleBusters[32];
            case "LB_W02_034":
                return LittleBusters[33];
            case "LB_W02_035":
                return LittleBusters[34];
            case "LB_W02_036":
                return LittleBusters[35];
            case "LB_W02_037":
                return LittleBusters[36];
            case "LB_W02_038":
                return LittleBusters[37];
            case "LB_W02_039":
                return LittleBusters[38];
            case "LB_W02_040":
                return LittleBusters[39];
            case "LB_W02_041":
                return LittleBusters[40];
            case "LB_W02_042":
                return LittleBusters[41];
            case "LB_W02_043":
                return LittleBusters[42];
            case "LB_W02_044":
                return LittleBusters[43];
            case "LB_W02_045":
                return LittleBusters[44];
            case "LB_W02_046":
                return LittleBusters[45];
            case "LB_W02_047":
                return LittleBusters[46];
            case "LB_W02_048":
                return LittleBusters[47];
            case "LB_W02_049":
                return LittleBusters[48];
            case "LB_W02_050":
                return LittleBusters[49];
            case "LB_W02_051":
                return LittleBusters[50];
            case "LB_W02_052":
                return LittleBusters[51];
            case "LB_W02_053":
                return LittleBusters[52];
            case "LB_W02_054":
                return LittleBusters[53];
            case "LB_W02_055":
                return LittleBusters[54];
            case "LB_W02_056":
                return LittleBusters[55];
            case "LB_W02_057":
                return LittleBusters[56];
            case "LB_W02_058":
                return LittleBusters[57];
            case "LB_W02_059":
                return LittleBusters[58];
            case "LB_W02_060":
                return LittleBusters[59];
            case "LB_W02_061":
                return LittleBusters[60];
            case "LB_W02_062":
                return LittleBusters[61];
            case "LB_W02_063":
                return LittleBusters[62];
            case "LB_W02_064":
                return LittleBusters[63];
            case "LB_W02_065":
                return LittleBusters[64];
            case "LB_W02_066":
                return LittleBusters[65];
            case "LB_W02_067":
                return LittleBusters[66];
            case "LB_W02_068":
                return LittleBusters[67];
            case "LB_W02_069":
                return LittleBusters[68];
            case "LB_W02_070":
                return LittleBusters[69];
            case "LB_W02_071":
                return LittleBusters[70];
            case "LB_W02_072":
                return LittleBusters[71];
            case "LB_W02_073":
                return LittleBusters[72];
            case "LB_W02_074":
                return LittleBusters[73];
            case "LB_W02_075":
                return LittleBusters[74];
            case "LB_W02_076":
                return LittleBusters[75];
            case "LB_W02_077":
                return LittleBusters[76];
            case "LB_W02_078":
                return LittleBusters[77];
            case "LB_W02_079":
                return LittleBusters[78];
            case "LB_W02_080":
                return LittleBusters[79];
            case "LB_W02_081":
                return LittleBusters[80];
            case "LB_W02_082":
                return LittleBusters[81];
            case "LB_W02_083":
                return LittleBusters[82];
            case "LB_W02_084":
                return LittleBusters[83];
            case "LB_W02_085":
                return LittleBusters[84];
            case "LB_W02_086":
                return LittleBusters[85];
            case "LB_W02_087":
                return LittleBusters[86];
            case "LB_W02_088":
                return LittleBusters[87];
            case "LB_W02_089":
                return LittleBusters[88];
            case "LB_W02_090":
                return LittleBusters[89];
            case "LB_W02_091":
                return LittleBusters[90];
            case "LB_W02_092":
                return LittleBusters[91];
            case "LB_W02_093":
                return LittleBusters[92];
            case "LB_W02_094":
                return LittleBusters[93];
            case "LB_W02_095":
                return LittleBusters[94];
            case "LB_W02_096":
                return LittleBusters[95];
            case "LB_W02_097":
                return LittleBusters[96];
            case "LB_W02_098":
                return LittleBusters[97];
            case "LB_W02_099":
                return LittleBusters[98];
            case "LB_W02_100":
                return LittleBusters[99];
            default:
                break;
        }
        return null;
    }
}
