using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using EnumController;

namespace ExtendUtil
{
    public class ExtendUtil
    {
        private StringValues stringValues = new StringValues();

        public string Explanation(EnumController.CardNo cardNo)
        {
            switch (cardNo)
            {
                case EnumController.CardNo.AT_WX02_A01:
                    return stringValues.AT_WX02_A01_Explanation;
                case EnumController.CardNo.AT_WX02_A02:
                    return stringValues.AT_WX02_A02_Explanation;
                case EnumController.CardNo.AT_WX02_A03:
                    return stringValues.AT_WX02_A03_Explanation;
                case EnumController.CardNo.AT_WX02_A04:
                    return stringValues.AT_WX02_A04_Explanation;
                case EnumController.CardNo.AT_WX02_A05:
                    return stringValues.AT_WX02_A05_Explanation;
                case EnumController.CardNo.AT_WX02_A06:
                    return stringValues.AT_WX02_A06_Explanation;
                case EnumController.CardNo.AT_WX02_A07:
                    return stringValues.AT_WX02_A07_Explanation;
                case EnumController.CardNo.AT_WX02_A08:
                    return stringValues.AT_WX02_A08_Explanation;
                case EnumController.CardNo.AT_WX02_A09:
                    return stringValues.AT_WX02_A09_Explanation;
                case EnumController.CardNo.AT_WX02_A10:
                    return stringValues.AT_WX02_A10_Explanation;
                case EnumController.CardNo.AT_WX02_A11:
                    return stringValues.AT_WX02_A11_Explanation;
                case EnumController.CardNo.AT_WX02_A12:
                    return stringValues.AT_WX02_A12_Explanation;
                case EnumController.CardNo.AT_WX02_A13:
                    return stringValues.AT_WX02_A13_Explanation;
                case EnumController.CardNo.DC_W01_01T:
                    return stringValues.DC_W01_01T_Explanation;
                case EnumController.CardNo.DC_W01_02T:
                    return stringValues.DC_W01_02T_Explanation;
                case EnumController.CardNo.DC_W01_03T:
                    return stringValues.DC_W01_03T_Explanation;
                case EnumController.CardNo.DC_W01_04T:
                    return stringValues.DC_W01_04T_Explanation;
                case EnumController.CardNo.DC_W01_05T:
                    return stringValues.DC_W01_05T_Explanation;
                case EnumController.CardNo.DC_W01_06T:
                    return stringValues.DC_W01_06T_Explanation;
                case EnumController.CardNo.DC_W01_07T:
                    return stringValues.DC_W01_07T_Explanation;
                case EnumController.CardNo.DC_W01_08T:
                    return stringValues.DC_W01_08T_Explanation;
                case EnumController.CardNo.DC_W01_09T:
                    return stringValues.DC_W01_09T_Explanation;
                case EnumController.CardNo.DC_W01_10T:
                    return stringValues.DC_W01_10T_Explanation;
                case EnumController.CardNo.DC_W01_11T:
                    return stringValues.DC_W01_11T_Explanation;
                case EnumController.CardNo.DC_W01_12T:
                    return stringValues.DC_W01_12T_Explanation;
                case EnumController.CardNo.DC_W01_13T:
                    return stringValues.DC_W01_13T_Explanation;
                case EnumController.CardNo.DC_W01_14T:
                    return stringValues.DC_W01_14T_Explanation;
                case EnumController.CardNo.DC_W01_15T:
                    return stringValues.DC_W01_15T_Explanation;
                case EnumController.CardNo.DC_W01_16T:
                    return stringValues.DC_W01_16T_Explanation;
                case EnumController.CardNo.DC_W01_17T:
                    return stringValues.DC_W01_17T_Explanation;
                case EnumController.CardNo.DC_W01_18T:
                    return stringValues.DC_W01_18T_Explanation;
                case EnumController.CardNo.DC_W01_19T:
                    return stringValues.DC_W01_19T_Explanation;
                case EnumController.CardNo.DC_W01_20T:
                    return stringValues.DC_W01_20T_Explanation;
                case EnumController.CardNo.LB_W02_01T:
                    return stringValues.LB_W02_01T_Explanation;
                case EnumController.CardNo.LB_W02_02T:
                    return stringValues.LB_W02_02T_Explanation;
                case EnumController.CardNo.LB_W02_03T:
                    return stringValues.LB_W02_03T_Explanation;
                case EnumController.CardNo.LB_W02_04T:
                    return stringValues.LB_W02_04T_Explanation;
                case EnumController.CardNo.LB_W02_05T:
                    return stringValues.LB_W02_05T_Explanation;
                case EnumController.CardNo.LB_W02_06T:
                    return stringValues.LB_W02_06T_Explanation;
                case EnumController.CardNo.LB_W02_07T:
                    return stringValues.LB_W02_07T_Explanation;
                case EnumController.CardNo.LB_W02_08T:
                    return stringValues.LB_W02_08T_Explanation;
                case EnumController.CardNo.LB_W02_09T:
                    return stringValues.LB_W02_09T_Explanation;
                case EnumController.CardNo.LB_W02_10T:
                    return stringValues.LB_W02_10T_Explanation;
                case EnumController.CardNo.LB_W02_11T:
                    return stringValues.LB_W02_11T_Explanation;
                case EnumController.CardNo.LB_W02_12T:
                    return stringValues.LB_W02_12T_Explanation;
                case EnumController.CardNo.LB_W02_13T:
                    return stringValues.LB_W02_13T_Explanation;
                case EnumController.CardNo.LB_W02_14T:
                    return stringValues.LB_W02_14T_Explanation;
                case EnumController.CardNo.LB_W02_15T:
                    return stringValues.LB_W02_15T_Explanation;
                case EnumController.CardNo.LB_W02_16T:
                    return stringValues.LB_W02_16T_Explanation;
                case EnumController.CardNo.LB_W02_17T:
                    return stringValues.LB_W02_17T_Explanation;
                case EnumController.CardNo.LB_W02_18T:
                    return stringValues.LB_W02_18T_Explanation;
                case EnumController.CardNo.LB_W02_19T:
                    return stringValues.LB_W02_19T_Explanation;
                case EnumController.CardNo.LB_W02_20T:
                    return stringValues.LB_W02_20T_Explanation;
                case EnumController.CardNo.P3_S01_01T:
                    return stringValues.P3_S01_01T_Explanation;
                case EnumController.CardNo.P3_S01_02T:
                    return stringValues.P3_S01_02T_Explanation;
                case EnumController.CardNo.P3_S01_03T:
                    return stringValues.P3_S01_03T_Explanation;
                case EnumController.CardNo.P3_S01_04T:
                    return stringValues.P3_S01_04T_Explanation;
                case EnumController.CardNo.P3_S01_05T:
                    return stringValues.P3_S01_05T_Explanation;
                case EnumController.CardNo.P3_S01_06T:
                    return stringValues.P3_S01_06T_Explanation;
                case EnumController.CardNo.P3_S01_07T:
                    return stringValues.P3_S01_07T_Explanation;
                case EnumController.CardNo.P3_S01_08T:
                    return stringValues.P3_S01_08T_Explanation;
                case EnumController.CardNo.P3_S01_09T:
                    return stringValues.P3_S01_09T_Explanation;
                case EnumController.CardNo.P3_S01_10T:
                    return stringValues.P3_S01_10T_Explanation;
                case EnumController.CardNo.P3_S01_11T:
                    return stringValues.P3_S01_11T_Explanation;
                case EnumController.CardNo.P3_S01_12T:
                    return stringValues.P3_S01_12T_Explanation;
                case EnumController.CardNo.P3_S01_13T:
                    return stringValues.P3_S01_13T_Explanation;
                case EnumController.CardNo.P3_S01_14T:
                    return stringValues.P3_S01_14T_Explanation;
                case EnumController.CardNo.P3_S01_15T:
                    return stringValues.P3_S01_15T_Explanation;
                case EnumController.CardNo.P3_S01_16T:
                    return stringValues.P3_S01_16T_Explanation;
                case EnumController.CardNo.P3_S01_17T:
                    return stringValues.P3_S01_17T_Explanation;
                case EnumController.CardNo.P3_S01_18T:
                    return stringValues.P3_S01_18T_Explanation;
                case EnumController.CardNo.P3_S01_19T:
                    return stringValues.P3_S01_19T_Explanation;
                case EnumController.CardNo.P3_S01_20T:
                    return stringValues.P3_S01_20T_Explanation;
                default:
                    break;
            }
            switch (cardNo)
            {
                case EnumController.CardNo.P3_S01_001:
                    return stringValues.P3_S01_001_Explanation;
                case EnumController.CardNo.P3_S01_002:
                    return stringValues.P3_S01_002_Explanation;
                case EnumController.CardNo.P3_S01_003:
                    return stringValues.P3_S01_003_Explanation;
                case EnumController.CardNo.P3_S01_004:
                    return stringValues.P3_S01_004_Explanation;
                case EnumController.CardNo.P3_S01_005:
                    return stringValues.P3_S01_005_Explanation;
                case EnumController.CardNo.P3_S01_006:
                    return stringValues.P3_S01_006_Explanation;
                case EnumController.CardNo.P3_S01_007:
                    return stringValues.P3_S01_007_Explanation;
                case EnumController.CardNo.P3_S01_008:
                    return stringValues.P3_S01_008_Explanation;
                case EnumController.CardNo.P3_S01_009:
                    return stringValues.P3_S01_009_Explanation;
                case EnumController.CardNo.P3_S01_010:
                    return stringValues.P3_S01_010_Explanation;
                case EnumController.CardNo.P3_S01_011:
                    return stringValues.P3_S01_011_Explanation;
                case EnumController.CardNo.P3_S01_012:
                    return stringValues.P3_S01_012_Explanation;
                case EnumController.CardNo.P3_S01_013:
                    return stringValues.P3_S01_013_Explanation;
                case EnumController.CardNo.P3_S01_014:
                    return stringValues.P3_S01_014_Explanation;
                case EnumController.CardNo.P3_S01_015:
                    return stringValues.P3_S01_015_Explanation;
                case EnumController.CardNo.P3_S01_016:
                    return stringValues.P3_S01_016_Explanation;
                case EnumController.CardNo.P3_S01_017:
                    return stringValues.P3_S01_017_Explanation;
                case EnumController.CardNo.P3_S01_018:
                    return stringValues.P3_S01_018_Explanation;
                case EnumController.CardNo.P3_S01_019:
                    return stringValues.P3_S01_019_Explanation;
                case EnumController.CardNo.P3_S01_020:
                    return stringValues.P3_S01_020_Explanation;
                case EnumController.CardNo.P3_S01_021:
                    return stringValues.P3_S01_021_Explanation;
                case EnumController.CardNo.P3_S01_022:
                    return stringValues.P3_S01_022_Explanation;
                case EnumController.CardNo.P3_S01_023:
                    return stringValues.P3_S01_023_Explanation;
                case EnumController.CardNo.P3_S01_024:
                    return stringValues.P3_S01_024_Explanation;
                case EnumController.CardNo.P3_S01_025:
                    return stringValues.P3_S01_025_Explanation;
                case EnumController.CardNo.P3_S01_026:
                    return stringValues.P3_S01_026_Explanation;
                case EnumController.CardNo.P3_S01_027:
                    return stringValues.P3_S01_027_Explanation;
                case EnumController.CardNo.P3_S01_028:
                    return stringValues.P3_S01_028_Explanation;
                case EnumController.CardNo.P3_S01_029:
                    return stringValues.P3_S01_029_Explanation;
                case EnumController.CardNo.P3_S01_030:
                    return stringValues.P3_S01_030_Explanation;
                case EnumController.CardNo.P3_S01_031:
                    return stringValues.P3_S01_031_Explanation;
                case EnumController.CardNo.P3_S01_032:
                    return stringValues.P3_S01_032_Explanation;
                case EnumController.CardNo.P3_S01_033:
                    return stringValues.P3_S01_033_Explanation;
                case EnumController.CardNo.P3_S01_034:
                    return stringValues.P3_S01_034_Explanation;
                case EnumController.CardNo.P3_S01_035:
                    return stringValues.P3_S01_035_Explanation;
                case EnumController.CardNo.P3_S01_036:
                    return stringValues.P3_S01_036_Explanation;
                case EnumController.CardNo.P3_S01_037:
                    return stringValues.P3_S01_037_Explanation;
                case EnumController.CardNo.P3_S01_038:
                    return stringValues.P3_S01_038_Explanation;
                case EnumController.CardNo.P3_S01_039:
                    return stringValues.P3_S01_039_Explanation;
                case EnumController.CardNo.P3_S01_040:
                    return stringValues.P3_S01_040_Explanation;
                case EnumController.CardNo.P3_S01_041:
                    return stringValues.P3_S01_041_Explanation;
                case EnumController.CardNo.P3_S01_042:
                    return stringValues.P3_S01_042_Explanation;
                case EnumController.CardNo.P3_S01_043:
                    return stringValues.P3_S01_043_Explanation;
                case EnumController.CardNo.P3_S01_044:
                    return stringValues.P3_S01_044_Explanation;
                case EnumController.CardNo.P3_S01_045:
                    return stringValues.P3_S01_045_Explanation;
                case EnumController.CardNo.P3_S01_046:
                    return stringValues.P3_S01_046_Explanation;
                case EnumController.CardNo.P3_S01_047:
                    return stringValues.P3_S01_047_Explanation;
                case EnumController.CardNo.P3_S01_048:
                    return stringValues.P3_S01_048_Explanation;
                case EnumController.CardNo.P3_S01_049:
                    return stringValues.P3_S01_049_Explanation;
                case EnumController.CardNo.P3_S01_050:
                    return stringValues.P3_S01_050_Explanation;
                case EnumController.CardNo.P3_S01_051:
                    return stringValues.P3_S01_051_Explanation;
                case EnumController.CardNo.P3_S01_052:
                    return stringValues.P3_S01_052_Explanation;
                case EnumController.CardNo.P3_S01_053:
                    return stringValues.P3_S01_053_Explanation;
                case EnumController.CardNo.P3_S01_054:
                    return stringValues.P3_S01_054_Explanation;
                case EnumController.CardNo.P3_S01_055:
                    return stringValues.P3_S01_055_Explanation;
                case EnumController.CardNo.P3_S01_056:
                    return stringValues.P3_S01_056_Explanation;
                case EnumController.CardNo.P3_S01_057:
                    return stringValues.P3_S01_057_Explanation;
                case EnumController.CardNo.P3_S01_058:
                    return stringValues.P3_S01_058_Explanation;
                case EnumController.CardNo.P3_S01_059:
                    return stringValues.P3_S01_059_Explanation;
                case EnumController.CardNo.P3_S01_060:
                    return stringValues.P3_S01_060_Explanation;
                case EnumController.CardNo.P3_S01_061:
                    return stringValues.P3_S01_061_Explanation;
                case EnumController.CardNo.P3_S01_062:
                    return stringValues.P3_S01_062_Explanation;
                case EnumController.CardNo.P3_S01_063:
                    return stringValues.P3_S01_063_Explanation;
                case EnumController.CardNo.P3_S01_064:
                    return stringValues.P3_S01_064_Explanation;
                case EnumController.CardNo.P3_S01_065:
                    return stringValues.P3_S01_065_Explanation;
                case EnumController.CardNo.P3_S01_066:
                    return stringValues.P3_S01_066_Explanation;
                case EnumController.CardNo.P3_S01_067:
                    return stringValues.P3_S01_067_Explanation;
                case EnumController.CardNo.P3_S01_068:
                    return stringValues.P3_S01_068_Explanation;
                case EnumController.CardNo.P3_S01_069:
                    return stringValues.P3_S01_069_Explanation;
                case EnumController.CardNo.P3_S01_070:
                    return stringValues.P3_S01_070_Explanation;
                default:
                    break;
            }
            switch (cardNo)
            {
                case EnumController.CardNo.P3_S01_071:
                    return stringValues.P3_S01_071_Explanation;
                case EnumController.CardNo.P3_S01_072:
                    return stringValues.P3_S01_072_Explanation;
                case EnumController.CardNo.P3_S01_073:
                    return stringValues.P3_S01_073_Explanation;
                case EnumController.CardNo.P3_S01_074:
                    return stringValues.P3_S01_074_Explanation;
                case EnumController.CardNo.P3_S01_075:
                    return stringValues.P3_S01_075_Explanation;
                case EnumController.CardNo.P3_S01_076:
                    return stringValues.P3_S01_076_Explanation;
                case EnumController.CardNo.P3_S01_077:
                    return stringValues.P3_S01_077_Explanation;
                case EnumController.CardNo.P3_S01_078:
                    return stringValues.P3_S01_078_Explanation;
                case EnumController.CardNo.P3_S01_079:
                    return stringValues.P3_S01_079_Explanation;
                case EnumController.CardNo.P3_S01_080:
                    return stringValues.P3_S01_080_Explanation;
                case EnumController.CardNo.P3_S01_081:
                    return stringValues.P3_S01_081_Explanation;
                case EnumController.CardNo.P3_S01_082:
                    return stringValues.P3_S01_082_Explanation;
                case EnumController.CardNo.P3_S01_083:
                    return stringValues.P3_S01_083_Explanation;
                case EnumController.CardNo.P3_S01_084:
                    return stringValues.P3_S01_084_Explanation;
                case EnumController.CardNo.P3_S01_085:
                    return stringValues.P3_S01_085_Explanation;
                case EnumController.CardNo.P3_S01_086:
                    return stringValues.P3_S01_086_Explanation;
                case EnumController.CardNo.P3_S01_087:
                    return stringValues.P3_S01_087_Explanation;
                case EnumController.CardNo.P3_S01_088:
                    return stringValues.P3_S01_088_Explanation;
                case EnumController.CardNo.P3_S01_089:
                    return stringValues.P3_S01_089_Explanation;
                case EnumController.CardNo.P3_S01_090:
                    return stringValues.P3_S01_090_Explanation;
                case EnumController.CardNo.P3_S01_091:
                    return stringValues.P3_S01_091_Explanation;
                case EnumController.CardNo.P3_S01_092:
                    return stringValues.P3_S01_092_Explanation;
                case EnumController.CardNo.P3_S01_093:
                    return stringValues.P3_S01_093_Explanation;
                case EnumController.CardNo.P3_S01_094:
                    return stringValues.P3_S01_094_Explanation;
                case EnumController.CardNo.P3_S01_095:
                    return stringValues.P3_S01_095_Explanation;
                case EnumController.CardNo.P3_S01_096:
                    return stringValues.P3_S01_096_Explanation;
                case EnumController.CardNo.P3_S01_097:
                    return stringValues.P3_S01_097_Explanation;
                case EnumController.CardNo.P3_S01_098:
                    return stringValues.P3_S01_098_Explanation;
                case EnumController.CardNo.P3_S01_099:
                    return stringValues.P3_S01_099_Explanation;
                case EnumController.CardNo.P3_S01_100:
                    return stringValues.P3_S01_100_Explanation;

                default:
                    break;
            }
            return "";
        }

        public string CardNoConvertToString(EnumController.CardNo cardNo)
        {
            switch (cardNo)
            {
                case EnumController.CardNo.AT_WX02_A01:
                    return stringValues.AT_WX02_A01_CardNo;
                case EnumController.CardNo.AT_WX02_A02:
                    return stringValues.AT_WX02_A02_CardNo;
                case EnumController.CardNo.AT_WX02_A03:
                    return stringValues.AT_WX02_A03_CardNo;
                case EnumController.CardNo.AT_WX02_A04:
                    return stringValues.AT_WX02_A04_CardNo;
                case EnumController.CardNo.AT_WX02_A05:
                    return stringValues.AT_WX02_A05_CardNo;
                case EnumController.CardNo.AT_WX02_A06:
                    return stringValues.AT_WX02_A06_CardNo;
                case EnumController.CardNo.AT_WX02_A07:
                    return stringValues.AT_WX02_A07_CardNo;
                case EnumController.CardNo.AT_WX02_A08:
                    return stringValues.AT_WX02_A08_CardNo;
                case EnumController.CardNo.AT_WX02_A09:
                    return stringValues.AT_WX02_A09_CardNo;
                case EnumController.CardNo.AT_WX02_A10:
                    return stringValues.AT_WX02_A10_CardNo;
                case EnumController.CardNo.AT_WX02_A11:
                    return stringValues.AT_WX02_A11_CardNo;
                case EnumController.CardNo.AT_WX02_A12:
                    return stringValues.AT_WX02_A12_CardNo;
                case EnumController.CardNo.AT_WX02_A13:
                    return stringValues.AT_WX02_A13_CardNo;
                case EnumController.CardNo.DC_W01_01T:
                    return stringValues.DC_W01_01T_CardNo;
                case EnumController.CardNo.DC_W01_02T:
                    return stringValues.DC_W01_02T_CardNo;
                case EnumController.CardNo.DC_W01_03T:
                    return stringValues.DC_W01_03T_CardNo;
                case EnumController.CardNo.DC_W01_04T:
                    return stringValues.DC_W01_04T_CardNo;
                case EnumController.CardNo.DC_W01_05T:
                    return stringValues.DC_W01_05T_CardNo;
                case EnumController.CardNo.DC_W01_06T:
                    return stringValues.DC_W01_06T_CardNo;
                case EnumController.CardNo.DC_W01_07T:
                    return stringValues.DC_W01_07T_CardNo;
                case EnumController.CardNo.DC_W01_08T:
                    return stringValues.DC_W01_08T_CardNo;
                case EnumController.CardNo.DC_W01_09T:
                    return stringValues.DC_W01_09T_CardNo;
                case EnumController.CardNo.DC_W01_10T:
                    return stringValues.DC_W01_10T_CardNo;
                case EnumController.CardNo.DC_W01_11T:
                    return stringValues.DC_W01_11T_CardNo;
                case EnumController.CardNo.DC_W01_12T:
                    return stringValues.DC_W01_12T_CardNo;
                case EnumController.CardNo.DC_W01_13T:
                    return stringValues.DC_W01_13T_CardNo;
                case EnumController.CardNo.DC_W01_14T:
                    return stringValues.DC_W01_14T_CardNo;
                case EnumController.CardNo.DC_W01_15T:
                    return stringValues.DC_W01_15T_CardNo;
                case EnumController.CardNo.DC_W01_16T:
                    return stringValues.DC_W01_16T_CardNo;
                case EnumController.CardNo.DC_W01_17T:
                    return stringValues.DC_W01_17T_CardNo;
                case EnumController.CardNo.DC_W01_18T:
                    return stringValues.DC_W01_18T_CardNo;
                case EnumController.CardNo.DC_W01_19T:
                    return stringValues.DC_W01_19T_CardNo;
                case EnumController.CardNo.DC_W01_20T:
                    return stringValues.DC_W01_20T_CardNo;
                case EnumController.CardNo.LB_W02_01T:
                    return stringValues.LB_W02_01T_CardNo;
                case EnumController.CardNo.LB_W02_02T:
                    return stringValues.LB_W02_02T_CardNo;
                case EnumController.CardNo.LB_W02_03T:
                    return stringValues.LB_W02_03T_CardNo;
                case EnumController.CardNo.LB_W02_04T:
                    return stringValues.LB_W02_04T_CardNo;
                case EnumController.CardNo.LB_W02_05T:
                    return stringValues.LB_W02_05T_CardNo;
                case EnumController.CardNo.LB_W02_06T:
                    return stringValues.LB_W02_06T_CardNo;
                case EnumController.CardNo.LB_W02_07T:
                    return stringValues.LB_W02_07T_CardNo;
                case EnumController.CardNo.LB_W02_08T:
                    return stringValues.LB_W02_08T_CardNo;
                case EnumController.CardNo.LB_W02_09T:
                    return stringValues.LB_W02_09T_CardNo;
                case EnumController.CardNo.LB_W02_10T:
                    return stringValues.LB_W02_10T_CardNo;
                case EnumController.CardNo.LB_W02_11T:
                    return stringValues.LB_W02_11T_CardNo;
                case EnumController.CardNo.LB_W02_12T:
                    return stringValues.LB_W02_12T_CardNo;
                case EnumController.CardNo.LB_W02_13T:
                    return stringValues.LB_W02_13T_CardNo;
                case EnumController.CardNo.LB_W02_14T:
                    return stringValues.LB_W02_14T_CardNo;
                case EnumController.CardNo.LB_W02_15T:
                    return stringValues.LB_W02_15T_CardNo;
                case EnumController.CardNo.LB_W02_16T:
                    return stringValues.LB_W02_16T_CardNo;
                case EnumController.CardNo.LB_W02_17T:
                    return stringValues.LB_W02_17T_CardNo;
                case EnumController.CardNo.LB_W02_18T:
                    return stringValues.LB_W02_18T_CardNo;
                case EnumController.CardNo.LB_W02_19T:
                    return stringValues.LB_W02_19T_CardNo;
                case EnumController.CardNo.LB_W02_20T:
                    return stringValues.LB_W02_20T_CardNo;
                case EnumController.CardNo.P3_S01_01T:
                    return stringValues.P3_S01_01T_CardNo;
                case EnumController.CardNo.P3_S01_02T:
                    return stringValues.P3_S01_02T_CardNo;
                case EnumController.CardNo.P3_S01_03T:
                    return stringValues.P3_S01_03T_CardNo;
                case EnumController.CardNo.P3_S01_04T:
                    return stringValues.P3_S01_04T_CardNo;
                case EnumController.CardNo.P3_S01_05T:
                    return stringValues.P3_S01_05T_CardNo;
                case EnumController.CardNo.P3_S01_06T:
                    return stringValues.P3_S01_06T_CardNo;
                case EnumController.CardNo.P3_S01_07T:
                    return stringValues.P3_S01_07T_CardNo;
                case EnumController.CardNo.P3_S01_08T:
                    return stringValues.P3_S01_08T_CardNo;
                case EnumController.CardNo.P3_S01_09T:
                    return stringValues.P3_S01_09T_CardNo;
                case EnumController.CardNo.P3_S01_10T:
                    return stringValues.P3_S01_10T_CardNo;
                case EnumController.CardNo.P3_S01_11T:
                    return stringValues.P3_S01_11T_CardNo;
                case EnumController.CardNo.P3_S01_12T:
                    return stringValues.P3_S01_12T_CardNo;
                case EnumController.CardNo.P3_S01_13T:
                    return stringValues.P3_S01_13T_CardNo;
                case EnumController.CardNo.P3_S01_14T:
                    return stringValues.P3_S01_14T_CardNo;
                case EnumController.CardNo.P3_S01_15T:
                    return stringValues.P3_S01_15T_CardNo;
                case EnumController.CardNo.P3_S01_16T:
                    return stringValues.P3_S01_16T_CardNo;
                case EnumController.CardNo.P3_S01_17T:
                    return stringValues.P3_S01_17T_CardNo;
                case EnumController.CardNo.P3_S01_18T:
                    return stringValues.P3_S01_18T_CardNo;
                case EnumController.CardNo.P3_S01_19T:
                    return stringValues.P3_S01_19T_CardNo;
                case EnumController.CardNo.P3_S01_20T:
                    return stringValues.P3_S01_20T_CardNo;
                default:
                    break;
            }
            switch (cardNo)
            {
                case EnumController.CardNo.P3_S01_001:
                    return stringValues.P3_S01_001_CardNo;
                case EnumController.CardNo.P3_S01_002:
                    return stringValues.P3_S01_002_CardNo;
                case EnumController.CardNo.P3_S01_003:
                    return stringValues.P3_S01_003_CardNo;
                case EnumController.CardNo.P3_S01_004:
                    return stringValues.P3_S01_004_CardNo;
                case EnumController.CardNo.P3_S01_005:
                    return stringValues.P3_S01_005_CardNo;
                case EnumController.CardNo.P3_S01_006:
                    return stringValues.P3_S01_006_CardNo;
                case EnumController.CardNo.P3_S01_007:
                    return stringValues.P3_S01_007_CardNo;
                case EnumController.CardNo.P3_S01_008:
                    return stringValues.P3_S01_008_CardNo;
                case EnumController.CardNo.P3_S01_009:
                    return stringValues.P3_S01_009_CardNo;
                case EnumController.CardNo.P3_S01_010:
                    return stringValues.P3_S01_010_CardNo;
                case EnumController.CardNo.P3_S01_011:
                    return stringValues.P3_S01_011_CardNo;
                case EnumController.CardNo.P3_S01_012:
                    return stringValues.P3_S01_012_CardNo;
                case EnumController.CardNo.P3_S01_013:
                    return stringValues.P3_S01_013_CardNo;
                case EnumController.CardNo.P3_S01_014:
                    return stringValues.P3_S01_014_CardNo;
                case EnumController.CardNo.P3_S01_015:
                    return stringValues.P3_S01_015_CardNo;
                case EnumController.CardNo.P3_S01_016:
                    return stringValues.P3_S01_016_CardNo;
                case EnumController.CardNo.P3_S01_017:
                    return stringValues.P3_S01_017_CardNo;
                case EnumController.CardNo.P3_S01_018:
                    return stringValues.P3_S01_018_CardNo;
                case EnumController.CardNo.P3_S01_019:
                    return stringValues.P3_S01_019_CardNo;
                case EnumController.CardNo.P3_S01_020:
                    return stringValues.P3_S01_020_CardNo;
                case EnumController.CardNo.P3_S01_021:
                    return stringValues.P3_S01_021_CardNo;
                case EnumController.CardNo.P3_S01_022:
                    return stringValues.P3_S01_022_CardNo;
                case EnumController.CardNo.P3_S01_023:
                    return stringValues.P3_S01_023_CardNo;
                case EnumController.CardNo.P3_S01_024:
                    return stringValues.P3_S01_024_CardNo;
                case EnumController.CardNo.P3_S01_025:
                    return stringValues.P3_S01_025_CardNo;
                case EnumController.CardNo.P3_S01_026:
                    return stringValues.P3_S01_026_CardNo;
                case EnumController.CardNo.P3_S01_027:
                    return stringValues.P3_S01_027_CardNo;
                case EnumController.CardNo.P3_S01_028:
                    return stringValues.P3_S01_028_CardNo;
                case EnumController.CardNo.P3_S01_029:
                    return stringValues.P3_S01_029_CardNo;
                case EnumController.CardNo.P3_S01_030:
                    return stringValues.P3_S01_030_CardNo;
                case EnumController.CardNo.P3_S01_031:
                    return stringValues.P3_S01_031_CardNo;
                case EnumController.CardNo.P3_S01_032:
                    return stringValues.P3_S01_032_CardNo;
                case EnumController.CardNo.P3_S01_033:
                    return stringValues.P3_S01_033_CardNo;
                case EnumController.CardNo.P3_S01_034:
                    return stringValues.P3_S01_034_CardNo;
                case EnumController.CardNo.P3_S01_035:
                    return stringValues.P3_S01_035_CardNo;
                case EnumController.CardNo.P3_S01_036:
                    return stringValues.P3_S01_036_CardNo;
                case EnumController.CardNo.P3_S01_037:
                    return stringValues.P3_S01_037_CardNo;
                case EnumController.CardNo.P3_S01_038:
                    return stringValues.P3_S01_038_CardNo;
                case EnumController.CardNo.P3_S01_039:
                    return stringValues.P3_S01_039_CardNo;
                case EnumController.CardNo.P3_S01_040:
                    return stringValues.P3_S01_040_CardNo;
                case EnumController.CardNo.P3_S01_041:
                    return stringValues.P3_S01_041_CardNo;
                case EnumController.CardNo.P3_S01_042:
                    return stringValues.P3_S01_042_CardNo;
                case EnumController.CardNo.P3_S01_043:
                    return stringValues.P3_S01_043_CardNo;
                case EnumController.CardNo.P3_S01_044:
                    return stringValues.P3_S01_044_CardNo;
                case EnumController.CardNo.P3_S01_045:
                    return stringValues.P3_S01_045_CardNo;
                case EnumController.CardNo.P3_S01_046:
                    return stringValues.P3_S01_046_CardNo;
                case EnumController.CardNo.P3_S01_047:
                    return stringValues.P3_S01_047_CardNo;
                case EnumController.CardNo.P3_S01_048:
                    return stringValues.P3_S01_048_CardNo;
                case EnumController.CardNo.P3_S01_049:
                    return stringValues.P3_S01_049_CardNo;
                case EnumController.CardNo.P3_S01_050:
                    return stringValues.P3_S01_050_CardNo;
                case EnumController.CardNo.P3_S01_051:
                    return stringValues.P3_S01_051_CardNo;
                case EnumController.CardNo.P3_S01_052:
                    return stringValues.P3_S01_052_CardNo;
                case EnumController.CardNo.P3_S01_053:
                    return stringValues.P3_S01_053_CardNo;
                case EnumController.CardNo.P3_S01_054:
                    return stringValues.P3_S01_054_CardNo;
                case EnumController.CardNo.P3_S01_055:
                    return stringValues.P3_S01_055_CardNo;
                case EnumController.CardNo.P3_S01_056:
                    return stringValues.P3_S01_056_CardNo;
                case EnumController.CardNo.P3_S01_057:
                    return stringValues.P3_S01_057_CardNo;
                case EnumController.CardNo.P3_S01_058:
                    return stringValues.P3_S01_058_CardNo;
                case EnumController.CardNo.P3_S01_059:
                    return stringValues.P3_S01_059_CardNo;
                case EnumController.CardNo.P3_S01_060:
                    return stringValues.P3_S01_060_CardNo;
                case EnumController.CardNo.P3_S01_061:
                    return stringValues.P3_S01_061_CardNo;
                case EnumController.CardNo.P3_S01_062:
                    return stringValues.P3_S01_062_CardNo;
                case EnumController.CardNo.P3_S01_063:
                    return stringValues.P3_S01_063_CardNo;
                case EnumController.CardNo.P3_S01_064:
                    return stringValues.P3_S01_064_CardNo;
                case EnumController.CardNo.P3_S01_065:
                    return stringValues.P3_S01_065_CardNo;
                case EnumController.CardNo.P3_S01_066:
                    return stringValues.P3_S01_066_CardNo;
                case EnumController.CardNo.P3_S01_067:
                    return stringValues.P3_S01_067_CardNo;
                case EnumController.CardNo.P3_S01_068:
                    return stringValues.P3_S01_068_CardNo;
                case EnumController.CardNo.P3_S01_069:
                    return stringValues.P3_S01_069_CardNo;
                case EnumController.CardNo.P3_S01_070:
                    return stringValues.P3_S01_070_CardNo;
                default:
                    break;
            }
            switch (cardNo)
            {
                case EnumController.CardNo.P3_S01_071:
                    return stringValues.P3_S01_071_CardNo;
                case EnumController.CardNo.P3_S01_072:
                    return stringValues.P3_S01_072_CardNo;
                case EnumController.CardNo.P3_S01_073:
                    return stringValues.P3_S01_073_CardNo;
                case EnumController.CardNo.P3_S01_074:
                    return stringValues.P3_S01_074_CardNo;
                case EnumController.CardNo.P3_S01_075:
                    return stringValues.P3_S01_075_CardNo;
                case EnumController.CardNo.P3_S01_076:
                    return stringValues.P3_S01_076_CardNo;
                case EnumController.CardNo.P3_S01_077:
                    return stringValues.P3_S01_077_CardNo;
                case EnumController.CardNo.P3_S01_078:
                    return stringValues.P3_S01_078_CardNo;
                case EnumController.CardNo.P3_S01_079:
                    return stringValues.P3_S01_079_CardNo;
                case EnumController.CardNo.P3_S01_080:
                    return stringValues.P3_S01_080_CardNo;
                case EnumController.CardNo.P3_S01_081:
                    return stringValues.P3_S01_081_CardNo;
                case EnumController.CardNo.P3_S01_082:
                    return stringValues.P3_S01_082_CardNo;
                case EnumController.CardNo.P3_S01_083:
                    return stringValues.P3_S01_083_CardNo;
                case EnumController.CardNo.P3_S01_084:
                    return stringValues.P3_S01_084_CardNo;
                case EnumController.CardNo.P3_S01_085:
                    return stringValues.P3_S01_085_CardNo;
                case EnumController.CardNo.P3_S01_086:
                    return stringValues.P3_S01_086_CardNo;
                case EnumController.CardNo.P3_S01_087:
                    return stringValues.P3_S01_087_CardNo;
                case EnumController.CardNo.P3_S01_088:
                    return stringValues.P3_S01_088_CardNo;
                case EnumController.CardNo.P3_S01_089:
                    return stringValues.P3_S01_089_CardNo;
                case EnumController.CardNo.P3_S01_090:
                    return stringValues.P3_S01_090_CardNo;
                case EnumController.CardNo.P3_S01_091:
                    return stringValues.P3_S01_091_CardNo;
                case EnumController.CardNo.P3_S01_092:
                    return stringValues.P3_S01_092_CardNo;
                case EnumController.CardNo.P3_S01_093:
                    return stringValues.P3_S01_093_CardNo;
                case EnumController.CardNo.P3_S01_094:
                    return stringValues.P3_S01_094_CardNo;
                case EnumController.CardNo.P3_S01_095:
                    return stringValues.P3_S01_095_CardNo;
                case EnumController.CardNo.P3_S01_096:
                    return stringValues.P3_S01_096_CardNo;
                case EnumController.CardNo.P3_S01_097:
                    return stringValues.P3_S01_097_CardNo;
                case EnumController.CardNo.P3_S01_098:
                    return stringValues.P3_S01_098_CardNo;
                case EnumController.CardNo.P3_S01_099:
                    return stringValues.P3_S01_099_CardNo;
                case EnumController.CardNo.P3_S01_100:
                    return stringValues.P3_S01_100_CardNo;
                default:
                    break;
            }
            return "";
        }

        public string AttributeConvertToString(EnumController.Attribute attribute)
        {
            switch (attribute)
            {
                case EnumController.Attribute.NONE:
                    return "特徴なし";
                case EnumController.Attribute.Ooo:
                    return "Ooo";
                case EnumController.Attribute.Hero:
                    return "Hero";
                case EnumController.Attribute.Royality:
                    return "Royality";
                case EnumController.Attribute.Vampire:
                    return "Vampire";
                case EnumController.Attribute.Animal:
                    return "動物";
                case EnumController.Attribute.Book:
                    return "本";
                case EnumController.Attribute.Shadow:
                    return "影";
                case EnumController.Attribute.ShrineMaiden:
                    return "巫女";
                case EnumController.Attribute.Sports:
                    return "スポーツ";
                case EnumController.Attribute.Sweets:
                    return "お菓子";
                case EnumController.Attribute.Magic:
                    return "魔法";
                case EnumController.Attribute.Music:
                    return "音楽";
                case EnumController.Attribute.Marble:
                    return "ビー玉";
                case EnumController.Attribute.Parasol:
                    return "日傘";
                case EnumController.Attribute.Comics:
                    return "漫画";
                case EnumController.Attribute.Glasses:
                    return "メガネ";
                case EnumController.Attribute.Teacher:
                    return "先生";
                case EnumController.Attribute.Banana:
                    return "バナナ";
                case EnumController.Attribute.Mecha:
                    return "メカ";
                case EnumController.Attribute.JapaneseClothes:
                    return "和服";
                case EnumController.Attribute.Pajamas:
                    return "パジャマ";
                case EnumController.Attribute.FairyTale:
                    return "童話";
                case EnumController.Attribute.Fan:
                    return "扇子";
                case EnumController.Attribute.God:
                    return "神";
                case EnumController.Attribute.Ramen:
                    return "ラーメン";
                case EnumController.Attribute.SchoolBag:
                    return "ランドセル";
                case EnumController.Attribute.StudentCouncil:
                    return "生徒会";
                case EnumController.Attribute.Weapon:
                    return "武器";
                case EnumController.Attribute.TVMailOrder:
                    return "テレビ通販";
                case EnumController.Attribute.Will:
                    return "遺言";
                case EnumController.Attribute.Death:
                    return "死";
                case EnumController.Attribute.Illness:
                    return "病気";
                case EnumController.Attribute.Swimsuit:
                    return "水着";
                case EnumController.Attribute.Twins:
                    return "双子";
                case EnumController.Attribute.Bullying:
                    return "いじめ";
                case EnumController.Attribute.Manager:
                    return "マネージャー";
                case EnumController.Attribute.OnlineGame:
                    return "ネトゲ";
                case EnumController.Attribute.Alcohol:
                    return "酒";
                case EnumController.Attribute.Gourmet:
                    return "グルメ";
                case EnumController.Attribute.Zen:
                    return "禅";
                default:
                    break;
            }
            return null;
        }
    }
}

