using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using EnumController;

namespace ExtendUtil
{
    public class ExtendUtil
    {
        private StringValues stringValues = new StringValues();

        public string Explanation(EnumController.CardNo cardNo)
        {
            switch (cardNo)
            {
                case EnumController.CardNo.AT_WX02_A01:
                    return stringValues.AT_WX02_A01_Explanation;
                case EnumController.CardNo.AT_WX02_A02:
                    return stringValues.AT_WX02_A02_Explanation;
                case EnumController.CardNo.AT_WX02_A03:
                    return stringValues.AT_WX02_A03_Explanation;
                case EnumController.CardNo.AT_WX02_A04:
                    return stringValues.AT_WX02_A04_Explanation;
                case EnumController.CardNo.AT_WX02_A05:
                    return stringValues.AT_WX02_A05_Explanation;
                case EnumController.CardNo.AT_WX02_A06:
                    return stringValues.AT_WX02_A06_Explanation;
                case EnumController.CardNo.AT_WX02_A07:
                    return stringValues.AT_WX02_A07_Explanation;
                case EnumController.CardNo.AT_WX02_A08:
                    return stringValues.AT_WX02_A08_Explanation;
                case EnumController.CardNo.AT_WX02_A09:
                    return stringValues.AT_WX02_A09_Explanation;
                case EnumController.CardNo.AT_WX02_A10:
                    return stringValues.AT_WX02_A10_Explanation;
                case EnumController.CardNo.AT_WX02_A11:
                    return stringValues.AT_WX02_A11_Explanation;
                case EnumController.CardNo.AT_WX02_A12:
                    return stringValues.AT_WX02_A12_Explanation;
                case EnumController.CardNo.AT_WX02_A13:
                    return stringValues.AT_WX02_A13_Explanation;
                case EnumController.CardNo.DC_W01_01T:
                    return stringValues.DC_W01_01T_Explanation;
                case EnumController.CardNo.DC_W01_02T:
                    return stringValues.DC_W01_02T_Explanation;
                case EnumController.CardNo.DC_W01_03T:
                    return stringValues.DC_W01_03T_Explanation;
                case EnumController.CardNo.DC_W01_04T:
                    return stringValues.DC_W01_04T_Explanation;
                case EnumController.CardNo.DC_W01_05T:
                    return stringValues.DC_W01_05T_Explanation;
                case EnumController.CardNo.DC_W01_06T:
                    return stringValues.DC_W01_06T_Explanation;
                case EnumController.CardNo.DC_W01_07T:
                    return stringValues.DC_W01_07T_Explanation;
                case EnumController.CardNo.DC_W01_08T:
                    return stringValues.DC_W01_08T_Explanation;
                case EnumController.CardNo.DC_W01_09T:
                    return stringValues.DC_W01_09T_Explanation;
                case EnumController.CardNo.DC_W01_10T:
                    return stringValues.DC_W01_10T_Explanation;
                case EnumController.CardNo.DC_W01_11T:
                    return stringValues.DC_W01_11T_Explanation;
                case EnumController.CardNo.DC_W01_12T:
                    return stringValues.DC_W01_12T_Explanation;
                case EnumController.CardNo.DC_W01_13T:
                    return stringValues.DC_W01_13T_Explanation;
                case EnumController.CardNo.DC_W01_14T:
                    return stringValues.DC_W01_14T_Explanation;
                case EnumController.CardNo.DC_W01_15T:
                    return stringValues.DC_W01_15T_Explanation;
                case EnumController.CardNo.DC_W01_16T:
                    return stringValues.DC_W01_16T_Explanation;
                case EnumController.CardNo.DC_W01_17T:
                    return stringValues.DC_W01_17T_Explanation;
                case EnumController.CardNo.DC_W01_18T:
                    return stringValues.DC_W01_18T_Explanation;
                case EnumController.CardNo.DC_W01_19T:
                    return stringValues.DC_W01_19T_Explanation;
                case EnumController.CardNo.DC_W01_20T:
                    return stringValues.DC_W01_20T_Explanation;
                case EnumController.CardNo.LB_W02_01T:
                    return stringValues.LB_W02_01T_Explanation;
                case EnumController.CardNo.LB_W02_02T:
                    return stringValues.LB_W02_02T_Explanation;
                case EnumController.CardNo.LB_W02_03T:
                    return stringValues.LB_W02_03T_Explanation;
                case EnumController.CardNo.LB_W02_04T:
                    return stringValues.LB_W02_04T_Explanation;
                case EnumController.CardNo.LB_W02_05T:
                    return stringValues.LB_W02_05T_Explanation;
                case EnumController.CardNo.LB_W02_06T:
                    return stringValues.LB_W02_06T_Explanation;
                case EnumController.CardNo.LB_W02_07T:
                    return stringValues.LB_W02_07T_Explanation;
                case EnumController.CardNo.LB_W02_08T:
                    return stringValues.LB_W02_08T_Explanation;
                case EnumController.CardNo.LB_W02_09T:
                    return stringValues.LB_W02_09T_Explanation;
                case EnumController.CardNo.LB_W02_10T:
                    return stringValues.LB_W02_10T_Explanation;
                case EnumController.CardNo.LB_W02_11T:
                    return stringValues.LB_W02_11T_Explanation;
                case EnumController.CardNo.LB_W02_12T:
                    return stringValues.LB_W02_12T_Explanation;
                case EnumController.CardNo.LB_W02_13T:
                    return stringValues.LB_W02_13T_Explanation;
                case EnumController.CardNo.LB_W02_14T:
                    return stringValues.LB_W02_14T_Explanation;
                case EnumController.CardNo.LB_W02_15T:
                    return stringValues.LB_W02_15T_Explanation;
                case EnumController.CardNo.LB_W02_16T:
                    return stringValues.LB_W02_16T_Explanation;
                case EnumController.CardNo.LB_W02_17T:
                    return stringValues.LB_W02_17T_Explanation;
                case EnumController.CardNo.LB_W02_18T:
                    return stringValues.LB_W02_18T_Explanation;
                case EnumController.CardNo.LB_W02_19T:
                    return stringValues.LB_W02_19T_Explanation;
                case EnumController.CardNo.LB_W02_20T:
                    return stringValues.LB_W02_20T_Explanation;
                case EnumController.CardNo.P3_S01_01T:
                    return stringValues.P3_S01_01T_Explanation;
                case EnumController.CardNo.P3_S01_02T:
                    return stringValues.P3_S01_02T_Explanation;
                case EnumController.CardNo.P3_S01_03T:
                    return stringValues.P3_S01_03T_Explanation;
                case EnumController.CardNo.P3_S01_04T:
                    return stringValues.P3_S01_04T_Explanation;
                case EnumController.CardNo.P3_S01_05T:
                    return stringValues.P3_S01_05T_Explanation;
                case EnumController.CardNo.P3_S01_06T:
                    return stringValues.P3_S01_06T_Explanation;
                case EnumController.CardNo.P3_S01_07T:
                    return stringValues.P3_S01_07T_Explanation;
                case EnumController.CardNo.P3_S01_08T:
                    return stringValues.P3_S01_08T_Explanation;
                case EnumController.CardNo.P3_S01_09T:
                    return stringValues.P3_S01_09T_Explanation;
                case EnumController.CardNo.P3_S01_10T:
                    return stringValues.P3_S01_10T_Explanation;
                case EnumController.CardNo.P3_S01_11T:
                    return stringValues.P3_S01_11T_Explanation;
                case EnumController.CardNo.P3_S01_12T:
                    return stringValues.P3_S01_12T_Explanation;
                case EnumController.CardNo.P3_S01_13T:
                    return stringValues.P3_S01_13T_Explanation;
                case EnumController.CardNo.P3_S01_14T:
                    return stringValues.P3_S01_14T_Explanation;
                case EnumController.CardNo.P3_S01_15T:
                    return stringValues.P3_S01_15T_Explanation;
                case EnumController.CardNo.P3_S01_16T:
                    return stringValues.P3_S01_16T_Explanation;
                case EnumController.CardNo.P3_S01_17T:
                    return stringValues.P3_S01_17T_Explanation;
                case EnumController.CardNo.P3_S01_18T:
                    return stringValues.P3_S01_18T_Explanation;
                case EnumController.CardNo.P3_S01_19T:
                    return stringValues.P3_S01_19T_Explanation;
                case EnumController.CardNo.P3_S01_20T:
                    return stringValues.P3_S01_20T_Explanation;
                default:
                    break;
            }
            return "";
        }

        public string CardNoConvertToString(EnumController.CardNo cardNo)
        {
            switch (cardNo)
            {
                case EnumController.CardNo.AT_WX02_A01:
                    return stringValues.AT_WX02_A01_CardNo;
                case EnumController.CardNo.AT_WX02_A02:
                    return stringValues.AT_WX02_A02_CardNo;
                case EnumController.CardNo.AT_WX02_A03:
                    return stringValues.AT_WX02_A03_CardNo;
                case EnumController.CardNo.AT_WX02_A04:
                    return stringValues.AT_WX02_A04_CardNo;
                case EnumController.CardNo.AT_WX02_A05:
                    return stringValues.AT_WX02_A05_CardNo;
                case EnumController.CardNo.AT_WX02_A06:
                    return stringValues.AT_WX02_A06_CardNo;
                case EnumController.CardNo.AT_WX02_A07:
                    return stringValues.AT_WX02_A07_CardNo;
                case EnumController.CardNo.AT_WX02_A08:
                    return stringValues.AT_WX02_A08_CardNo;
                case EnumController.CardNo.AT_WX02_A09:
                    return stringValues.AT_WX02_A09_CardNo;
                case EnumController.CardNo.AT_WX02_A10:
                    return stringValues.AT_WX02_A10_CardNo;
                case EnumController.CardNo.AT_WX02_A11:
                    return stringValues.AT_WX02_A11_CardNo;
                case EnumController.CardNo.AT_WX02_A12:
                    return stringValues.AT_WX02_A12_CardNo;
                case EnumController.CardNo.AT_WX02_A13:
                    return stringValues.AT_WX02_A13_CardNo;
                case EnumController.CardNo.DC_W01_01T:
                    return stringValues.DC_W01_01T_CardNo;
                case EnumController.CardNo.DC_W01_02T:
                    return stringValues.DC_W01_02T_CardNo;
                case EnumController.CardNo.DC_W01_03T:
                    return stringValues.DC_W01_03T_CardNo;
                case EnumController.CardNo.DC_W01_04T:
                    return stringValues.DC_W01_04T_CardNo;
                case EnumController.CardNo.DC_W01_05T:
                    return stringValues.DC_W01_05T_CardNo;
                case EnumController.CardNo.DC_W01_06T:
                    return stringValues.DC_W01_06T_CardNo;
                case EnumController.CardNo.DC_W01_07T:
                    return stringValues.DC_W01_07T_CardNo;
                case EnumController.CardNo.DC_W01_08T:
                    return stringValues.DC_W01_08T_CardNo;
                case EnumController.CardNo.DC_W01_09T:
                    return stringValues.DC_W01_09T_CardNo;
                case EnumController.CardNo.DC_W01_10T:
                    return stringValues.DC_W01_10T_CardNo;
                case EnumController.CardNo.DC_W01_11T:
                    return stringValues.DC_W01_11T_CardNo;
                case EnumController.CardNo.DC_W01_12T:
                    return stringValues.DC_W01_12T_CardNo;
                case EnumController.CardNo.DC_W01_13T:
                    return stringValues.DC_W01_13T_CardNo;
                case EnumController.CardNo.DC_W01_14T:
                    return stringValues.DC_W01_14T_CardNo;
                case EnumController.CardNo.DC_W01_15T:
                    return stringValues.DC_W01_15T_CardNo;
                case EnumController.CardNo.DC_W01_16T:
                    return stringValues.DC_W01_16T_CardNo;
                case EnumController.CardNo.DC_W01_17T:
                    return stringValues.DC_W01_17T_CardNo;
                case EnumController.CardNo.DC_W01_18T:
                    return stringValues.DC_W01_18T_CardNo;
                case EnumController.CardNo.DC_W01_19T:
                    return stringValues.DC_W01_19T_CardNo;
                case EnumController.CardNo.DC_W01_20T:
                    return stringValues.DC_W01_20T_CardNo;
                case EnumController.CardNo.LB_W02_01T:
                    return stringValues.LB_W02_01T_CardNo;
                case EnumController.CardNo.LB_W02_02T:
                    return stringValues.LB_W02_02T_CardNo;
                case EnumController.CardNo.LB_W02_03T:
                    return stringValues.LB_W02_03T_CardNo;
                case EnumController.CardNo.LB_W02_04T:
                    return stringValues.LB_W02_04T_CardNo;
                case EnumController.CardNo.LB_W02_05T:
                    return stringValues.LB_W02_05T_CardNo;
                case EnumController.CardNo.LB_W02_06T:
                    return stringValues.LB_W02_06T_CardNo;
                case EnumController.CardNo.LB_W02_07T:
                    return stringValues.LB_W02_07T_CardNo;
                case EnumController.CardNo.LB_W02_08T:
                    return stringValues.LB_W02_08T_CardNo;
                case EnumController.CardNo.LB_W02_09T:
                    return stringValues.LB_W02_09T_CardNo;
                case EnumController.CardNo.LB_W02_10T:
                    return stringValues.LB_W02_10T_CardNo;
                case EnumController.CardNo.LB_W02_11T:
                    return stringValues.LB_W02_11T_CardNo;
                case EnumController.CardNo.LB_W02_12T:
                    return stringValues.LB_W02_12T_CardNo;
                case EnumController.CardNo.LB_W02_13T:
                    return stringValues.LB_W02_13T_CardNo;
                case EnumController.CardNo.LB_W02_14T:
                    return stringValues.LB_W02_14T_CardNo;
                case EnumController.CardNo.LB_W02_15T:
                    return stringValues.LB_W02_15T_CardNo;
                case EnumController.CardNo.LB_W02_16T:
                    return stringValues.LB_W02_16T_CardNo;
                case EnumController.CardNo.LB_W02_17T:
                    return stringValues.LB_W02_17T_CardNo;
                case EnumController.CardNo.LB_W02_18T:
                    return stringValues.LB_W02_18T_CardNo;
                case EnumController.CardNo.LB_W02_19T:
                    return stringValues.LB_W02_19T_CardNo;
                case EnumController.CardNo.LB_W02_20T:
                    return stringValues.LB_W02_20T_CardNo;
                case EnumController.CardNo.P3_S01_01T:
                    return stringValues.P3_S01_01T_CardNo;
                case EnumController.CardNo.P3_S01_02T:
                    return stringValues.P3_S01_02T_CardNo;
                case EnumController.CardNo.P3_S01_03T:
                    return stringValues.P3_S01_03T_CardNo;
                case EnumController.CardNo.P3_S01_04T:
                    return stringValues.P3_S01_04T_CardNo;
                case EnumController.CardNo.P3_S01_05T:
                    return stringValues.P3_S01_05T_CardNo;
                case EnumController.CardNo.P3_S01_06T:
                    return stringValues.P3_S01_06T_CardNo;
                case EnumController.CardNo.P3_S01_07T:
                    return stringValues.P3_S01_07T_CardNo;
                case EnumController.CardNo.P3_S01_08T:
                    return stringValues.P3_S01_08T_CardNo;
                case EnumController.CardNo.P3_S01_09T:
                    return stringValues.P3_S01_09T_CardNo;
                case EnumController.CardNo.P3_S01_10T:
                    return stringValues.P3_S01_10T_CardNo;
                case EnumController.CardNo.P3_S01_11T:
                    return stringValues.P3_S01_11T_CardNo;
                case EnumController.CardNo.P3_S01_12T:
                    return stringValues.P3_S01_12T_CardNo;
                case EnumController.CardNo.P3_S01_13T:
                    return stringValues.P3_S01_13T_CardNo;
                case EnumController.CardNo.P3_S01_14T:
                    return stringValues.P3_S01_14T_CardNo;
                case EnumController.CardNo.P3_S01_15T:
                    return stringValues.P3_S01_15T_CardNo;
                case EnumController.CardNo.P3_S01_16T:
                    return stringValues.P3_S01_16T_CardNo;
                case EnumController.CardNo.P3_S01_17T:
                    return stringValues.P3_S01_17T_CardNo;
                case EnumController.CardNo.P3_S01_18T:
                    return stringValues.P3_S01_18T_CardNo;
                case EnumController.CardNo.P3_S01_19T:
                    return stringValues.P3_S01_19T_CardNo;
                case EnumController.CardNo.P3_S01_20T:
                    return stringValues.P3_S01_20T_CardNo;
                default:
                    break;
            }
            return "";
        }

        public string AttributeConvertToString(EnumController.Attribute attribute)
        {
            switch (attribute)
            {
                case EnumController.Attribute.NONE:
                    return "特徴なし";
                case EnumController.Attribute.Ooo:
                    return "Ooo";
                case EnumController.Attribute.Hero:
                    return "Hero";
                case EnumController.Attribute.Royality:
                    return "Royality";
                case EnumController.Attribute.Vampire:
                    return "Vampire";
                case EnumController.Attribute.Animal:
                    return "動物";
                case EnumController.Attribute.Book:
                    return "本";
                case EnumController.Attribute.Shadow:
                    return "影";
                case EnumController.Attribute.ShrineMaiden:
                    return "巫女";
                case EnumController.Attribute.Sports:
                    return "スポーツ";
                case EnumController.Attribute.Sweets:
                    return "お菓子";
                case EnumController.Attribute.Magic:
                    return "魔法";
                case EnumController.Attribute.Music:
                    return "音楽";
                case EnumController.Attribute.Marble:
                    return "ビー玉";
                case EnumController.Attribute.Parasol:
                    return "日傘";
                case EnumController.Attribute.Comics:
                    return "漫画";
                case EnumController.Attribute.Glasses:
                    return "メガネ";
                case EnumController.Attribute.Teacher:
                    return "先生";
                case EnumController.Attribute.Banana:
                    return "バナナ";
                case EnumController.Attribute.Mecha:
                    return "メカ";
                case EnumController.Attribute.JapaneseClothes:
                    return "和服";
                case EnumController.Attribute.Pajamas:
                    return "パジャマ";
                case EnumController.Attribute.FairyTale:
                    return "童話";
                case EnumController.Attribute.Fan:
                    return "扇子";
                case EnumController.Attribute.God:
                    return "神";
                case EnumController.Attribute.Ramen:
                    return "ラーメン";
                case EnumController.Attribute.SchoolBag:
                    return "ランドセル";
                case EnumController.Attribute.StudentCouncil:
                    return "生徒会";
                case EnumController.Attribute.Weapon:
                    return "武器";
                case EnumController.Attribute.TVMailOrder:
                    return "テレビ通販";
                case EnumController.Attribute.Will:
                    return "遺言";
                default:
                    break;
            }
            return null;
        }
    }
}

